apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "host-manager.labels" . | nindent 4 }}
  name: {{ include "host-manager.fullname" . }}-{{ .Release.Namespace }}
roleRef:
  {{- if not .Values.roleRef.name }}
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "host-manager.fullname" . }}
  {{- else }}
  apiGroup: {{ .Values.roleRef.apiGroup }}
  kind: {{ .Values.roleRef.kind }}
  name: {{ .Values.roleRef.name }}
  {{- end }}
subjects:
  - kind: ServiceAccount
    name: {{ include "host-manager.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
