apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "kdex-host-manager.labels" . | nindent 4 }}
  name: {{ include "kdex-host-manager.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |
    {{- toYaml .Values.config | nindent 4 }}
