apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    checksum/config: {{ .Values.config | toJson | sha256sum }}
  labels:
    {{- include "host-manager.labels" . | nindent 4 }}
  name: {{ include "host-manager.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "host-manager.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ .Values.config | toJson | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "host-manager.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}

          args:
            - --health-probe-bind-address=:8081
            - --webserver-bind-address=:8090
            - --focal-host={{ .Values.focalHost }}
            - --service-name={{ include "host-manager.fullname" . }}
            {{- with .Values.proxy }}
            {{- with .dialTimeout }}
            - --proxy-dial-timeout={{ . }}
            {{- end }}
            {{- with .responseHeaderTimeout }}
            - --proxy-response-header-timeout={{ . }}
            {{- end }}
            {{- with .idleConnTimeout }}
            - --proxy-idle-conn-timeout={{ . }}
            {{- end }}
            {{- end }}
            {{- with .Values.extraArgs }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          env:
            - name: KUBERNETES_SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
            {{- if .Values.valkey.enabled }}
            - name: CACHE_ADDRESS
              value: {{ include "host-manager.fullname" . }}-valkey:6379
            {{- end }}
            {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          ports:
            - name: server
              containerPort: 8090
              protocol: TCP
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          volumeMounts:
            - mountPath: /config.yaml
              name: config
              subPath: config.yaml
            {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.valkey.enabled }}
      initContainers:
        - command:
          - bash
          - -c
          - |
              trap "echo 'Received signal to terminate.'; exit 0" SIGINT SIGTERM

              until timeout 2 bash -c '</dev/tcp/{{ include "host-manager.fullname" . }}-valkey/6379' 2>/dev/null
              do
                  echo "Waiting for {{ include "host-manager.fullname" . }}-valkey..."

                  sleep 2
              done
          image: ghcr.io/kdex-tech/cli-tools:0.3.9
          imagePullPolicy: IfNotPresent
          name: wait-on-valkey
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.schedulingGates }}
      schedulingGates:
        {{- range $value := . }}
        - name: {{ $value }}
        {{- end }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ include "host-manager.serviceAccountName" . }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "host-manager.fullname" . }}
        {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
