package controller

import (
	"context"

	"github.com/kdex-tech/host-manager/internal"
	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/api/meta"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/util/intstr"
	kdexv1alpha1 "kdex.dev/crds/api/v1alpha1"
	"sigs.k8s.io/controller-runtime/pkg/client"
)

var _ = Describe("KDexFunction Controller", func() {
	Context("When reconciling a KDexFunction", func() {
		const resourceName = "test-function"
		ctx := context.Background()

		AfterEach(func() {
			cleanupResources(namespace)
		})

		It("should fail if hostRef.name is empty", func() {
			resource := &kdexv1alpha1.KDexFunction{
				ObjectMeta: metav1.ObjectMeta{
					Name:      resourceName,
					Namespace: namespace,
				},
				Spec: kdexv1alpha1.KDexFunctionSpec{
					API: kdexv1alpha1.API{
						BasePath: "/v1/api",
						Paths: map[string]kdexv1alpha1.PathItem{
							"/v1/api/test": {},
						},
					},
				},
			}

			err := k8sClient.Create(ctx, resource)
			Expect(err).To(HaveOccurred())
			Expect(err.Error()).To(ContainSubstring("hostRef.name must not be empty"))
		})

		It("should fail if basePath does not match regex", func() {
			resource := &kdexv1alpha1.KDexFunction{
				ObjectMeta: metav1.ObjectMeta{
					Name:      resourceName,
					Namespace: namespace,
				},
				Spec: kdexv1alpha1.KDexFunctionSpec{
					HostRef: corev1.LocalObjectReference{Name: focalHost},
					API: kdexv1alpha1.API{
						BasePath: "/invalid", // only one segment, but regex is ^/\w+/\w+
						Paths: map[string]kdexv1alpha1.PathItem{
							"/invalid/test": {},
						},
					},
				},
			}

			err := k8sClient.Create(ctx, resource)
			Expect(err).To(HaveOccurred())
			Expect(err.Error()).To(ContainSubstring("match"))
		})

		It("should not create with invalid JSON OpenAPI", func() {
			resource := &kdexv1alpha1.KDexFunction{
				ObjectMeta: metav1.ObjectMeta{
					Name:      resourceName,
					Namespace: namespace,
				},
				Spec: kdexv1alpha1.KDexFunctionSpec{
					HostRef: corev1.LocalObjectReference{Name: focalHost},
					Metadata: kdexv1alpha1.KDexFunctionMetadata{
						AutoGenerated: true,
					},
					API: kdexv1alpha1.API{
						BasePath: "/v1/api",
						Paths: map[string]kdexv1alpha1.PathItem{
							"/v1/api/test": {
								Get: &runtime.RawExtension{
									Raw: []byte(`{`),
								},
							},
						},
					},
				},
			}

			err := k8sClient.Create(ctx, resource)
			Expect(err).To(HaveOccurred())
			Expect(err.Error()).To(ContainSubstring("json: error calling MarshalJSON for type *runtime.RawExtension: unexpected end of JSON input"))
		})

		It("becomes OpenAPIValid", func() {
			resource := &kdexv1alpha1.KDexFunction{
				ObjectMeta: metav1.ObjectMeta{
					Name:      resourceName,
					Namespace: namespace,
				},
				Spec: kdexv1alpha1.KDexFunctionSpec{
					HostRef: corev1.LocalObjectReference{Name: focalHost},
					Metadata: kdexv1alpha1.KDexFunctionMetadata{
						AutoGenerated: true,
					},
					API: kdexv1alpha1.API{
						BasePath: "/v1/api",
						Paths: map[string]kdexv1alpha1.PathItem{
							"/v1/api/test": {},
						},
					},
				},
			}

			Expect(k8sClient.Create(ctx, resource)).To(Succeed())

			addOrUpdateInternalHost(
				ctx, k8sClient,
				kdexv1alpha1.KDexInternalHost{
					ObjectMeta: metav1.ObjectMeta{
						Name:      focalHost,
						Namespace: namespace,
					},
					Spec: kdexv1alpha1.KDexInternalHostSpec{
						KDexHostSpec: kdexv1alpha1.KDexHostSpec{
							BrandName:    "KDex Tech",
							DevMode:      true,
							ModulePolicy: kdexv1alpha1.LooseModulePolicy,
							Organization: "KDex Tech Inc.",
							Routing: kdexv1alpha1.Routing{
								Domains: []string{
									"kdex.dev",
								},
							},
						},
					},
				},
			)

			assertResourceReady(
				ctx, k8sClient, focalHost, namespace,
				&kdexv1alpha1.KDexInternalHost{}, true)

			faasAdaptor := &kdexv1alpha1.KDexClusterFaaSAdaptor{
				ObjectMeta: metav1.ObjectMeta{
					Labels: map[string]string{
						"kdex.dev/default": "true",
					},
					Name:      "kdex-default-faas-adaptor-knative",
					Namespace: namespace,
				},
				Spec: kdexv1alpha1.KDexFaaSAdaptorSpec{
					Builders: []kdexv1alpha1.Builder{
						{
							Languages: []string{"go"},
							Name:      "tiny",
							BuilderRef: kdexv1alpha1.KDexObjectReference{
								Kind: "ClusterBuilder",
								Name: "tiny",
							},
						},
					},
					DefaultBuilderGenerator: "tiny/go",
					Deployer: kdexv1alpha1.Deployer{
						Image: "deployer",
					},
					Generators: []kdexv1alpha1.Generator{
						{
							Language: "java",
							Image:    "java",
						},
					},
					Provider: "knative",
				},
			}
			Expect(k8sClient.Create(ctx, faasAdaptor)).To(Succeed())

			Eventually(func(g Gomega) {
				fetched := &kdexv1alpha1.KDexFunction{}
				err := k8sClient.Get(ctx, client.ObjectKey{Name: resource.Name, Namespace: namespace}, fetched)
				g.Expect(err).NotTo(HaveOccurred())
				g.Expect(fetched.Status.State).To(Equal(kdexv1alpha1.KDexFunctionStateOpenAPIValid))
			}, "10s", "1s").Should(Succeed())
		})

		It("becomes BuildValid", func() {
			resource := &kdexv1alpha1.KDexFunction{
				ObjectMeta: metav1.ObjectMeta{
					Name:      resourceName,
					Namespace: namespace,
				},
				Spec: kdexv1alpha1.KDexFunctionSpec{
					HostRef: corev1.LocalObjectReference{Name: focalHost},
					Metadata: kdexv1alpha1.KDexFunctionMetadata{
						AutoGenerated: true,
					},
					API: kdexv1alpha1.API{
						BasePath: "/v1/api",
						Paths: map[string]kdexv1alpha1.PathItem{
							"/v1/api/test": {},
						},
					},
					Origin: kdexv1alpha1.FunctionOrigin{
						Generator: &kdexv1alpha1.Generator{
							Image:    "ghcr.io/kdex-dev/kdex-function-generator-go:latest",
							Language: "go",
						},
					},
				},
			}

			Expect(k8sClient.Create(ctx, resource)).To(Succeed())

			addOrUpdateInternalHost(
				ctx, k8sClient,
				kdexv1alpha1.KDexInternalHost{
					ObjectMeta: metav1.ObjectMeta{
						Name:      focalHost,
						Namespace: namespace,
					},
					Spec: kdexv1alpha1.KDexInternalHostSpec{
						KDexHostSpec: kdexv1alpha1.KDexHostSpec{
							BrandName:    "KDex Tech",
							DevMode:      true,
							ModulePolicy: kdexv1alpha1.LooseModulePolicy,
							Organization: "KDex Tech Inc.",
							Routing: kdexv1alpha1.Routing{
								Domains: []string{
									"kdex.dev",
								},
							},
						},
					},
				},
			)

			assertResourceReady(
				ctx, k8sClient, focalHost, namespace,
				&kdexv1alpha1.KDexInternalHost{}, true)

			faasAdaptor := &kdexv1alpha1.KDexClusterFaaSAdaptor{
				ObjectMeta: metav1.ObjectMeta{
					Labels: map[string]string{
						"kdex.dev/default": "true",
					},
					Name:      "kdex-default-faas-adaptor-knative",
					Namespace: namespace,
				},
				Spec: kdexv1alpha1.KDexFaaSAdaptorSpec{
					Builders: []kdexv1alpha1.Builder{
						{
							Languages: []string{"go"},
							Name:      "tiny",
							BuilderRef: kdexv1alpha1.KDexObjectReference{
								Kind: "ClusterBuilder",
								Name: "tiny",
							},
						},
					},
					DefaultBuilderGenerator: "tiny/go",
					Deployer: kdexv1alpha1.Deployer{
						Image: "deployer",
					},
					Generators: []kdexv1alpha1.Generator{
						{
							Language: "go",
							Image:    "ghcr.io/kdex-dev/kdex-function-generator-go:latest",
						},
					},
					Provider: "knative",
				},
			}
			Expect(k8sClient.Create(ctx, faasAdaptor)).To(Succeed())

			Eventually(func(g Gomega) {
				fetched := &kdexv1alpha1.KDexFunction{}
				err := k8sClient.Get(ctx, client.ObjectKey{Name: resource.Name, Namespace: namespace}, fetched)
				g.Expect(err).NotTo(HaveOccurred())
				g.Expect(
					meta.IsStatusConditionTrue(
						fetched.Status.Conditions,
						string(kdexv1alpha1.ConditionTypeDegraded),
					),
				).To(BeTrue())
				g.Expect(
					meta.IsStatusConditionFalse(
						fetched.Status.Conditions,
						string(kdexv1alpha1.ConditionTypeProgressing),
					),
				).To(BeTrue())
				g.Expect(fetched.Status.State).To(Equal(kdexv1alpha1.KDexFunctionStateBuildValid))
			}, "10s", "1s").Should(Succeed())
		})

		It("becomes SourceAvailable", func() {
			resource := &kdexv1alpha1.KDexFunction{
				ObjectMeta: metav1.ObjectMeta{
					Name:      resourceName,
					Namespace: namespace,
				},
				Spec: kdexv1alpha1.KDexFunctionSpec{
					HostRef: corev1.LocalObjectReference{Name: focalHost},
					Metadata: kdexv1alpha1.KDexFunctionMetadata{
						AutoGenerated: true,
					},
					API: kdexv1alpha1.API{
						BasePath: "/v1/api",
						Paths: map[string]kdexv1alpha1.PathItem{
							"/v1/api/test": {},
						},
					},
					Origin: kdexv1alpha1.FunctionOrigin{
						Source: &kdexv1alpha1.Source{
							Builder: &kdexv1alpha1.Builder{
								Languages: []string{"go"},
								Name:      "tiny",
								BuilderRef: kdexv1alpha1.KDexObjectReference{
									Kind: "ClusterBuilder",
									Name: "tiny",
								},
							},
							Path:       "baz",
							Repository: "foo",
							Revision:   "bar",
						},
					},
				},
			}

			Expect(k8sClient.Create(ctx, resource)).To(Succeed())

			addOrUpdateInternalHost(
				ctx, k8sClient,
				kdexv1alpha1.KDexInternalHost{
					ObjectMeta: metav1.ObjectMeta{
						Name:      focalHost,
						Namespace: namespace,
					},
					Spec: kdexv1alpha1.KDexInternalHostSpec{
						KDexHostSpec: kdexv1alpha1.KDexHostSpec{
							BrandName:    "KDex Tech",
							DevMode:      true,
							ModulePolicy: kdexv1alpha1.LooseModulePolicy,
							Organization: "KDex Tech Inc.",
							Routing: kdexv1alpha1.Routing{
								Domains: []string{
									"kdex.dev",
								},
							},
						},
					},
				},
			)

			assertResourceReady(
				ctx, k8sClient, focalHost, namespace,
				&kdexv1alpha1.KDexInternalHost{}, true)

			faasAdaptor := &kdexv1alpha1.KDexClusterFaaSAdaptor{
				ObjectMeta: metav1.ObjectMeta{
					Labels: map[string]string{
						"kdex.dev/default": "true",
					},
					Name:      "kdex-default-faas-adaptor-knative",
					Namespace: namespace,
				},
				Spec: kdexv1alpha1.KDexFaaSAdaptorSpec{
					Builders: []kdexv1alpha1.Builder{
						{
							Languages: []string{"go"},
							Name:      "tiny",
							BuilderRef: kdexv1alpha1.KDexObjectReference{
								Kind: "ClusterBuilder",
								Name: "tiny",
							},
						},
					},
					DefaultBuilderGenerator: "tiny/go",
					Deployer: kdexv1alpha1.Deployer{
						Image: "deployer",
					},
					Generators: []kdexv1alpha1.Generator{
						{
							Language: "go",
							Image:    "ghcr.io/kdex-dev/kdex-function-generator-go:latest",
						},
					},
					Provider: "knative",
				},
			}
			Expect(k8sClient.Create(ctx, faasAdaptor)).To(Succeed())

			Eventually(func(g Gomega) {
				fetched := &kdexv1alpha1.KDexFunction{}
				err := k8sClient.Get(ctx, client.ObjectKey{Name: resource.Name, Namespace: namespace}, fetched)
				g.Expect(err).NotTo(HaveOccurred())
				g.Expect(
					meta.IsStatusConditionFalse(
						fetched.Status.Conditions,
						string(kdexv1alpha1.ConditionTypeDegraded),
					),
				).To(BeTrue())
				g.Expect(
					meta.IsStatusConditionTrue(
						fetched.Status.Conditions,
						string(kdexv1alpha1.ConditionTypeProgressing),
					),
				).To(BeTrue())
				g.Expect(fetched.Status.State).To(Equal(kdexv1alpha1.KDexFunctionStateSourceAvailable))
			}, "10s", "1s").Should(Succeed())
		})

		It("forwards spec.origin.source.builder.serviceAccountName to the kpack Image", func() {
			const customBuildSA = "custom-build-sa"

			resource := &kdexv1alpha1.KDexFunction{
				ObjectMeta: metav1.ObjectMeta{
					Name:      resourceName,
					Namespace: namespace,
				},
				Spec: kdexv1alpha1.KDexFunctionSpec{
					HostRef: corev1.LocalObjectReference{Name: focalHost},
					Metadata: kdexv1alpha1.KDexFunctionMetadata{
						AutoGenerated: true,
					},
					API: kdexv1alpha1.API{
						BasePath: "/v1/api",
						Paths: map[string]kdexv1alpha1.PathItem{
							"/v1/api/test": {},
						},
					},
					Origin: kdexv1alpha1.FunctionOrigin{
						Source: &kdexv1alpha1.Source{
							Builder: &kdexv1alpha1.Builder{
								Languages: []string{"go"},
								Name:      "tiny",
								BuilderRef: kdexv1alpha1.KDexObjectReference{
									Kind: "ClusterBuilder",
									Name: "tiny",
								},
								ServiceAccountName: customBuildSA,
							},
							Path:       "baz",
							Repository: "foo",
							Revision:   "bar",
						},
					},
				},
			}

			Expect(k8sClient.Create(ctx, resource)).To(Succeed())

			addOrUpdateInternalHost(
				ctx, k8sClient,
				kdexv1alpha1.KDexInternalHost{
					ObjectMeta: metav1.ObjectMeta{
						Name:      focalHost,
						Namespace: namespace,
					},
					Spec: kdexv1alpha1.KDexInternalHostSpec{
						KDexHostSpec: kdexv1alpha1.KDexHostSpec{
							BrandName:    "KDex Tech",
							DevMode:      true,
							ModulePolicy: kdexv1alpha1.LooseModulePolicy,
							Organization: "KDex Tech Inc.",
							Routing: kdexv1alpha1.Routing{
								Domains: []string{
									"kdex.dev",
								},
							},
						},
					},
				},
			)

			assertResourceReady(
				ctx, k8sClient, focalHost, namespace,
				&kdexv1alpha1.KDexInternalHost{}, true)

			faasAdaptor := &kdexv1alpha1.KDexClusterFaaSAdaptor{
				ObjectMeta: metav1.ObjectMeta{
					Labels: map[string]string{
						"kdex.dev/default": "true",
					},
					Name:      "kdex-default-faas-adaptor-knative",
					Namespace: namespace,
				},
				Spec: kdexv1alpha1.KDexFaaSAdaptorSpec{
					Builders: []kdexv1alpha1.Builder{
						{
							Languages: []string{"go"},
							Name:      "tiny",
							BuilderRef: kdexv1alpha1.KDexObjectReference{
								Kind: "ClusterBuilder",
								Name: "tiny",
							},
						},
					},
					DefaultBuilderGenerator: "tiny/go",
					Deployer: kdexv1alpha1.Deployer{
						Image: "deployer",
					},
					Generators: []kdexv1alpha1.Generator{
						{
							Language: "go",
							Image:    "ghcr.io/kdex-dev/kdex-function-generator-go:latest",
						},
					},
					Provider: "knative",
				},
			}
			Expect(k8sClient.Create(ctx, faasAdaptor)).To(Succeed())

			kImageName := focalHost + "-" + resource.Name
			Eventually(func(g Gomega) {
				kImage := &unstructured.Unstructured{}
				kImage.SetGroupVersionKind(internal.KPackImageGVK)
				err := k8sClient.Get(ctx, client.ObjectKey{Name: kImageName, Namespace: namespace}, kImage)
				g.Expect(err).NotTo(HaveOccurred())
				sa, found, err := unstructured.NestedString(kImage.Object, "spec", "serviceAccountName")
				g.Expect(err).NotTo(HaveOccurred())
				g.Expect(found).To(BeTrue())
				g.Expect(sa).To(Equal(customBuildSA))
			}, "10s", "1s").Should(Succeed())
		})

		It("forwards spec.origin.source.builder.{Tolerations,NodeSelector,Resources} to the kpack Image", func() {
			resource := &kdexv1alpha1.KDexFunction{
				ObjectMeta: metav1.ObjectMeta{
					Name:      resourceName,
					Namespace: namespace,
				},
				Spec: kdexv1alpha1.KDexFunctionSpec{
					HostRef: corev1.LocalObjectReference{Name: focalHost},
					Metadata: kdexv1alpha1.KDexFunctionMetadata{
						AutoGenerated: true,
					},
					API: kdexv1alpha1.API{
						BasePath: "/v1/api",
						Paths: map[string]kdexv1alpha1.PathItem{
							"/v1/api/test": {},
						},
					},
					Origin: kdexv1alpha1.FunctionOrigin{
						Source: &kdexv1alpha1.Source{
							Builder: &kdexv1alpha1.Builder{
								Languages: []string{"go"},
								Name:      "tiny",
								BuilderRef: kdexv1alpha1.KDexObjectReference{
									Kind: "ClusterBuilder",
									Name: "tiny",
								},
								Tolerations: []corev1.Toleration{{
									Key:      "cloud.google.com/gke-spot",
									Operator: corev1.TolerationOpEqual,
									Value:    "true",
									Effect:   corev1.TaintEffectNoSchedule,
								}},
								NodeSelector: map[string]string{
									"component": "kpack-build",
								},
							},
							Path:       "baz",
							Repository: "foo",
							Revision:   "bar",
						},
					},
				},
			}
			Expect(k8sClient.Create(ctx, resource)).To(Succeed())

			addOrUpdateInternalHost(
				ctx, k8sClient,
				kdexv1alpha1.KDexInternalHost{
					ObjectMeta: metav1.ObjectMeta{Name: focalHost, Namespace: namespace},
					Spec: kdexv1alpha1.KDexInternalHostSpec{
						KDexHostSpec: kdexv1alpha1.KDexHostSpec{
							BrandName: "KDex Tech", DevMode: true,
							ModulePolicy: kdexv1alpha1.LooseModulePolicy,
							Organization: "KDex Tech Inc.",
							Routing:      kdexv1alpha1.Routing{Domains: []string{"kdex.dev"}},
						},
					},
				},
			)
			assertResourceReady(ctx, k8sClient, focalHost, namespace, &kdexv1alpha1.KDexInternalHost{}, true)

			faasAdaptor := &kdexv1alpha1.KDexClusterFaaSAdaptor{
				ObjectMeta: metav1.ObjectMeta{
					Labels:    map[string]string{"kdex.dev/default": "true"},
					Name:      "kdex-default-faas-adaptor-knative",
					Namespace: namespace,
				},
				Spec: kdexv1alpha1.KDexFaaSAdaptorSpec{
					Builders: []kdexv1alpha1.Builder{{
						Languages:  []string{"go"},
						Name:       "tiny",
						BuilderRef: kdexv1alpha1.KDexObjectReference{Kind: "ClusterBuilder", Name: "tiny"},
					}},
					DefaultBuilderGenerator: "tiny/go",
					Deployer:                kdexv1alpha1.Deployer{Image: "deployer"},
					Generators: []kdexv1alpha1.Generator{{
						Language: "go",
						Image:    "ghcr.io/kdex-dev/kdex-function-generator-go:latest",
					}},
					Provider: "knative",
				},
			}
			Expect(k8sClient.Create(ctx, faasAdaptor)).To(Succeed())

			kImageName := focalHost + "-" + resource.Name
			Eventually(func(g Gomega) {
				kImage := &unstructured.Unstructured{}
				kImage.SetGroupVersionKind(internal.KPackImageGVK)
				err := k8sClient.Get(ctx, client.ObjectKey{Name: kImageName, Namespace: namespace}, kImage)
				g.Expect(err).NotTo(HaveOccurred())

				tols, found, err := unstructured.NestedSlice(kImage.Object, "spec", "build", "tolerations")
				g.Expect(err).NotTo(HaveOccurred())
				g.Expect(found).To(BeTrue())
				g.Expect(tols).To(HaveLen(1))
				tol := tols[0].(map[string]any)
				g.Expect(tol["key"]).To(Equal("cloud.google.com/gke-spot"))
				g.Expect(tol["value"]).To(Equal("true"))
				g.Expect(tol["effect"]).To(Equal("NoSchedule"))

				ns, found, err := unstructured.NestedStringMap(kImage.Object, "spec", "build", "nodeSelector")
				g.Expect(err).NotTo(HaveOccurred())
				g.Expect(found).To(BeTrue())
				g.Expect(ns).To(HaveKeyWithValue("component", "kpack-build"))
			}, "10s", "1s").Should(Succeed())
		})

		It("falls back to FaaSAdaptor.DefaultBuilderGenerator when Source.Builder is nil", func() {
			// Source with NO Builder set — simulates the generator-mode happy path
			// where the codegen Job populates Status.Source.{Repository,Revision,Path}
			// but not Builder.
			resource := &kdexv1alpha1.KDexFunction{
				ObjectMeta: metav1.ObjectMeta{
					Name:      resourceName,
					Namespace: namespace,
				},
				Spec: kdexv1alpha1.KDexFunctionSpec{
					HostRef: corev1.LocalObjectReference{Name: focalHost},
					Metadata: kdexv1alpha1.KDexFunctionMetadata{
						AutoGenerated: true,
					},
					API: kdexv1alpha1.API{
						BasePath: "/v1/api",
						Paths: map[string]kdexv1alpha1.PathItem{
							"/v1/api/test": {},
						},
					},
					Origin: kdexv1alpha1.FunctionOrigin{
						Source: &kdexv1alpha1.Source{
							// Builder intentionally omitted.
							Path:       "baz",
							Repository: "foo",
							Revision:   "bar",
						},
					},
				},
			}
			Expect(k8sClient.Create(ctx, resource)).To(Succeed())

			addOrUpdateInternalHost(
				ctx, k8sClient,
				kdexv1alpha1.KDexInternalHost{
					ObjectMeta: metav1.ObjectMeta{Name: focalHost, Namespace: namespace},
					Spec: kdexv1alpha1.KDexInternalHostSpec{
						KDexHostSpec: kdexv1alpha1.KDexHostSpec{
							BrandName: "KDex Tech", DevMode: true,
							ModulePolicy: kdexv1alpha1.LooseModulePolicy,
							Organization: "KDex Tech Inc.",
							Routing:      kdexv1alpha1.Routing{Domains: []string{"kdex.dev"}},
						},
					},
				},
			)
			assertResourceReady(ctx, k8sClient, focalHost, namespace, &kdexv1alpha1.KDexInternalHost{}, true)

			faasAdaptor := &kdexv1alpha1.KDexClusterFaaSAdaptor{
				ObjectMeta: metav1.ObjectMeta{
					Labels:    map[string]string{"kdex.dev/default": "true"},
					Name:      "kdex-default-faas-adaptor-knative",
					Namespace: namespace,
				},
				Spec: kdexv1alpha1.KDexFaaSAdaptorSpec{
					Builders: []kdexv1alpha1.Builder{{
						Languages:  []string{"go"},
						Name:       "tiny",
						BuilderRef: kdexv1alpha1.KDexObjectReference{Kind: "ClusterBuilder", Name: "tiny-fallback"},
					}},
					DefaultBuilderGenerator: "tiny/go",
					Deployer:                kdexv1alpha1.Deployer{Image: "deployer"},
					Generators: []kdexv1alpha1.Generator{{
						Language: "go",
						Image:    "ghcr.io/kdex-dev/kdex-function-generator-go:latest",
					}},
					Provider: "knative",
				},
			}
			Expect(k8sClient.Create(ctx, faasAdaptor)).To(Succeed())

			kImageName := focalHost + "-" + resource.Name
			Eventually(func(g Gomega) {
				kImage := &unstructured.Unstructured{}
				kImage.SetGroupVersionKind(internal.KPackImageGVK)
				err := k8sClient.Get(ctx, client.ObjectKey{Name: kImageName, Namespace: namespace}, kImage)
				g.Expect(err).NotTo(HaveOccurred())
				name, found, err := unstructured.NestedString(kImage.Object, "spec", "builder", "name")
				g.Expect(err).NotTo(HaveOccurred())
				g.Expect(found).To(BeTrue())
				g.Expect(name).To(Equal("tiny-fallback"))
			}, "10s", "1s").Should(Succeed())
		})

		It("becomes ExecutableAvailable", func() {
			resource := &kdexv1alpha1.KDexFunction{
				ObjectMeta: metav1.ObjectMeta{
					Name:      resourceName,
					Namespace: namespace,
				},
				Spec: kdexv1alpha1.KDexFunctionSpec{
					HostRef: corev1.LocalObjectReference{Name: focalHost},
					Metadata: kdexv1alpha1.KDexFunctionMetadata{
						AutoGenerated: true,
					},
					API: kdexv1alpha1.API{
						BasePath: "/v1/api",
						Paths: map[string]kdexv1alpha1.PathItem{
							"/v1/api/test": {},
						},
					},
					Origin: kdexv1alpha1.FunctionOrigin{
						Executable: &kdexv1alpha1.Executable{
							Image: "foo",
						},
					},
				},
			}

			Expect(k8sClient.Create(ctx, resource)).To(Succeed())

			addOrUpdateInternalHost(
				ctx, k8sClient,
				kdexv1alpha1.KDexInternalHost{
					ObjectMeta: metav1.ObjectMeta{
						Name:      focalHost,
						Namespace: namespace,
					},
					Spec: kdexv1alpha1.KDexInternalHostSpec{
						KDexHostSpec: kdexv1alpha1.KDexHostSpec{
							BrandName:    "KDex Tech",
							DevMode:      true,
							ModulePolicy: kdexv1alpha1.LooseModulePolicy,
							Organization: "KDex Tech Inc.",
							Routing: kdexv1alpha1.Routing{
								Domains: []string{
									"kdex.dev",
								},
							},
						},
					},
				},
			)

			assertResourceReady(
				ctx, k8sClient, focalHost, namespace,
				&kdexv1alpha1.KDexInternalHost{}, true)

			faasAdaptor := &kdexv1alpha1.KDexClusterFaaSAdaptor{
				ObjectMeta: metav1.ObjectMeta{
					Labels: map[string]string{
						"kdex.dev/default": "true",
					},
					Name:      "kdex-default-faas-adaptor-knative",
					Namespace: namespace,
				},
				Spec: kdexv1alpha1.KDexFaaSAdaptorSpec{
					Builders: []kdexv1alpha1.Builder{
						{
							Languages: []string{"go"},
							Name:      "tiny",
							BuilderRef: kdexv1alpha1.KDexObjectReference{
								Kind: "ClusterBuilder",
								Name: "tiny",
							},
						},
					},
					DefaultBuilderGenerator: "tiny/go",
					Deployer: kdexv1alpha1.Deployer{
						Image: "deployer",
					},
					Generators: []kdexv1alpha1.Generator{
						{
							Language: "go",
							Image:    "ghcr.io/kdex-dev/kdex-function-generator-go:latest",
						},
					},
					Provider: "knative",
				},
			}
			Expect(k8sClient.Create(ctx, faasAdaptor)).To(Succeed())

			Eventually(func(g Gomega) {
				fetched := &kdexv1alpha1.KDexFunction{}
				err := k8sClient.Get(ctx, client.ObjectKey{Name: resource.Name, Namespace: namespace}, fetched)
				g.Expect(err).NotTo(HaveOccurred())
				g.Expect(fetched.Status.State).To(Equal(kdexv1alpha1.KDexFunctionStateExecutableAvailable))
				// Regression: state=ExecutableAvailable must imply
				// status.executable is populated so the deployer Job
				// path (which reads Status.Executable, not Spec.Origin)
				// can resolve the image. Bug filed as kdex-tech/
				// host-manager#24 — handleOpenAPIValid + handleBuildValid
				// used to short-circuit the state transition without
				// copying Spec.Origin.Executable into Status.Executable.
				g.Expect(fetched.Status.Executable).NotTo(BeNil(),
					"Status.Executable must be populated when state=ExecutableAvailable")
				g.Expect(fetched.Status.Executable.Image).To(Equal("foo"))
			}, "10s", "1s").Should(Succeed())
		})

		It("becomes FunctionDeployed", func() {
			Skip("Not ready yet")

			resource := &kdexv1alpha1.KDexFunction{
				ObjectMeta: metav1.ObjectMeta{
					Name:      resourceName,
					Namespace: namespace,
				},
				Spec: kdexv1alpha1.KDexFunctionSpec{
					HostRef: corev1.LocalObjectReference{Name: focalHost},
					Metadata: kdexv1alpha1.KDexFunctionMetadata{
						AutoGenerated: true,
					},
					API: kdexv1alpha1.API{
						BasePath: "/v1/api",
						Paths: map[string]kdexv1alpha1.PathItem{
							"/v1/api/test": {},
						},
					},
				},
			}

			Expect(k8sClient.Create(ctx, resource)).To(Succeed())

			addOrUpdateInternalHost(
				ctx, k8sClient,
				kdexv1alpha1.KDexInternalHost{
					ObjectMeta: metav1.ObjectMeta{
						Name:      focalHost,
						Namespace: namespace,
					},
					Spec: kdexv1alpha1.KDexInternalHostSpec{
						KDexHostSpec: kdexv1alpha1.KDexHostSpec{
							BrandName:    "KDex Tech",
							DevMode:      true,
							ModulePolicy: kdexv1alpha1.LooseModulePolicy,
							Organization: "KDex Tech Inc.",
							Routing: kdexv1alpha1.Routing{
								Domains: []string{
									"kdex.dev",
								},
							},
						},
					},
				},
			)

			assertResourceReady(
				ctx, k8sClient, focalHost, namespace,
				&kdexv1alpha1.KDexInternalHost{}, true)

			faasAdaptor := &kdexv1alpha1.KDexClusterFaaSAdaptor{
				ObjectMeta: metav1.ObjectMeta{
					Labels: map[string]string{
						"kdex.dev/default": "true",
					},
					Name:      "kdex-default-faas-adaptor-knative",
					Namespace: namespace,
				},
				Spec: kdexv1alpha1.KDexFaaSAdaptorSpec{
					Builders: []kdexv1alpha1.Builder{
						{
							Languages: []string{"go"},
							Name:      "tiny",
							BuilderRef: kdexv1alpha1.KDexObjectReference{
								Kind: "ClusterBuilder",
								Name: "tiny",
							},
						},
					},
					DefaultBuilderGenerator: "tiny/go",
					Deployer: kdexv1alpha1.Deployer{
						Image: "deployer",
					},
					Generators: []kdexv1alpha1.Generator{
						{
							Language: "go",
							Image:    "ghcr.io/kdex-dev/kdex-function-generator-go:latest",
						},
					},
					Provider: "knative",
				},
			}
			Expect(k8sClient.Create(ctx, faasAdaptor)).To(Succeed())

			patch := client.MergeFrom(resource.DeepCopy())
			resource.Status.URL = "https://foo.bar"
			resource.Status.ObservedGeneration = resource.Generation
			Expect(k8sClient.Status().Patch(ctx, resource, patch)).To(Succeed())

			Eventually(func(g Gomega) {
				fetched := &kdexv1alpha1.KDexFunction{}
				err := k8sClient.Get(ctx, client.ObjectKey{Name: resource.Name, Namespace: namespace}, fetched)
				g.Expect(err).NotTo(HaveOccurred())
				g.Expect(fetched.Status.State).To(Equal(kdexv1alpha1.KDexFunctionStateFunctionDeployed))
				g.Expect(
					meta.IsStatusConditionFalse(
						fetched.Status.Conditions,
						string(kdexv1alpha1.ConditionTypeDegraded),
					),
				).To(BeTrue())
				g.Expect(
					meta.IsStatusConditionFalse(
						fetched.Status.Conditions,
						string(kdexv1alpha1.ConditionTypeProgressing),
					),
				).To(BeTrue())
				g.Expect(
					meta.IsStatusConditionTrue(
						fetched.Status.Conditions,
						string(kdexv1alpha1.ConditionTypeReady),
					),
				).To(BeTrue())
				cond := meta.FindStatusCondition(
					fetched.Status.Conditions,
					string(kdexv1alpha1.ConditionTypeProgressing),
				)
				g.Expect(cond.Message).To(Equal("Reconciliation successful"))
			}, "10s", "1s").Should(Succeed())
		})
	})
})

var _ = Describe("KDexFunction CEL validation", func() {
	const namespace = "default"
	const focalHost = "test-host"

	Context("spec.backend admission", func() {
		ctx := context.Background()

		AfterEach(func() {
			cleanupResources(namespace)
		})

		It("rejects a function with both origin and backend set", func() {
			fn := &kdexv1alpha1.KDexFunction{
				ObjectMeta: metav1.ObjectMeta{
					Name:      "fn-both",
					Namespace: namespace,
				},
				Spec: kdexv1alpha1.KDexFunctionSpec{
					HostRef: corev1.LocalObjectReference{Name: focalHost},
					API: kdexv1alpha1.API{
						BasePath: "/v1/docs",
						Paths: map[string]kdexv1alpha1.PathItem{
							"/v1/docs/find": {Get: &runtime.RawExtension{Raw: []byte("{}")}},
						},
					},
					Origin: kdexv1alpha1.FunctionOrigin{
						Executable: &kdexv1alpha1.Executable{Image: "ghcr.io/example/fn:v1"},
					},
					Backend: &kdexv1alpha1.FunctionBackend{
						Type:    kdexv1alpha1.FunctionBackendTypeService,
						Service: &kdexv1alpha1.ServiceBackend{Name: "svc", Port: intstr.FromInt(80)},
					},
				},
			}
			err := k8sClient.Create(ctx, fn)
			Expect(err).To(HaveOccurred())
			Expect(err.Error()).To(ContainSubstring("mutually exclusive"))
		})

		It("rejects backend type=Service without backend.service", func() {
			fn := &kdexv1alpha1.KDexFunction{
				ObjectMeta: metav1.ObjectMeta{
					Name:      "fn-missing-service",
					Namespace: namespace,
				},
				Spec: kdexv1alpha1.KDexFunctionSpec{
					HostRef: corev1.LocalObjectReference{Name: focalHost},
					API: kdexv1alpha1.API{
						BasePath: "/v1/docs",
						Paths: map[string]kdexv1alpha1.PathItem{
							"/v1/docs/find": {Get: &runtime.RawExtension{Raw: []byte("{}")}},
						},
					},
					Backend: &kdexv1alpha1.FunctionBackend{
						Type: kdexv1alpha1.FunctionBackendTypeService,
					},
				},
			}
			err := k8sClient.Create(ctx, fn)
			Expect(err).To(HaveOccurred())
			Expect(err.Error()).To(ContainSubstring("service is required when type is Service"))
		})

		It("rejects service.path without leading slash", func() {
			fn := &kdexv1alpha1.KDexFunction{
				ObjectMeta: metav1.ObjectMeta{
					Name:      "fn-bad-path",
					Namespace: namespace,
				},
				Spec: kdexv1alpha1.KDexFunctionSpec{
					HostRef: corev1.LocalObjectReference{Name: focalHost},
					API: kdexv1alpha1.API{
						BasePath: "/v1/docs",
						Paths: map[string]kdexv1alpha1.PathItem{
							"/v1/docs/find": {Get: &runtime.RawExtension{Raw: []byte("{}")}},
						},
					},
					Backend: &kdexv1alpha1.FunctionBackend{
						Type: kdexv1alpha1.FunctionBackendTypeService,
						Service: &kdexv1alpha1.ServiceBackend{
							Name: "svc",
							Port: intstr.FromInt(80),
							Path: "api", // missing leading slash
						},
					},
				},
			}
			err := k8sClient.Create(ctx, fn)
			Expect(err).To(HaveOccurred())
		})

		It("accepts a minimal Service-backed function", func() {
			fn := &kdexv1alpha1.KDexFunction{
				ObjectMeta: metav1.ObjectMeta{
					Name:      "fn-minimal",
					Namespace: namespace,
				},
				Spec: kdexv1alpha1.KDexFunctionSpec{
					HostRef: corev1.LocalObjectReference{Name: focalHost},
					API: kdexv1alpha1.API{
						BasePath: "/v1/docs",
						Paths: map[string]kdexv1alpha1.PathItem{
							"/v1/docs/find": {Get: &runtime.RawExtension{Raw: []byte("{}")}},
						},
					},
					Backend: &kdexv1alpha1.FunctionBackend{
						Type:    kdexv1alpha1.FunctionBackendTypeService,
						Service: &kdexv1alpha1.ServiceBackend{Name: "svc", Port: intstr.FromInt(80)},
					},
				},
			}
			Expect(k8sClient.Create(ctx, fn)).To(Succeed())
		})

		It("accepts named-port service", func() {
			fn := &kdexv1alpha1.KDexFunction{
				ObjectMeta: metav1.ObjectMeta{
					Name:      "fn-named-port",
					Namespace: namespace,
				},
				Spec: kdexv1alpha1.KDexFunctionSpec{
					HostRef: corev1.LocalObjectReference{Name: focalHost},
					API: kdexv1alpha1.API{
						BasePath: "/v1/docs",
						Paths: map[string]kdexv1alpha1.PathItem{
							"/v1/docs/find": {Get: &runtime.RawExtension{Raw: []byte("{}")}},
						},
					},
					Backend: &kdexv1alpha1.FunctionBackend{
						Type:    kdexv1alpha1.FunctionBackendTypeService,
						Service: &kdexv1alpha1.ServiceBackend{Name: "svc", Port: intstr.FromString("http")},
					},
				},
			}
			Expect(k8sClient.Create(ctx, fn)).To(Succeed())
		})
	})
})
