package controller

import (
	"context"

	"github.com/kdex-tech/host-manager/internal"
	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
	corev1 "k8s.io/api/core/v1"
	discoveryv1 "k8s.io/api/discovery/v1"
	"k8s.io/apimachinery/pkg/api/meta"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/util/intstr"
	"k8s.io/utils/ptr"
	kdexv1alpha1 "kdex.dev/crds/api/v1alpha1"
	"sigs.k8s.io/controller-runtime/pkg/client"
)

// ensureFocalHost creates the focal KDexInternalHost so the function
// reconciler can resolve hostRef. It uses addOrUpdateInternalHost with a
// minimal valid KDexHostSpec (the Required fields on KDexHostSpec mean an
// empty Spec is rejected at admission).
func ensureFocalHost(ctx context.Context, ns, name string) {
	addOrUpdateInternalHost(
		ctx, k8sClient,
		kdexv1alpha1.KDexInternalHost{
			ObjectMeta: metav1.ObjectMeta{Name: name, Namespace: ns},
			Spec: kdexv1alpha1.KDexInternalHostSpec{
				KDexHostSpec: kdexv1alpha1.KDexHostSpec{
					BrandName:    "KDex Tech",
					DevMode:      true,
					ModulePolicy: kdexv1alpha1.LooseModulePolicy,
					Organization: "KDex Tech Inc.",
					Routing: kdexv1alpha1.Routing{
						Domains: []string{"kdex.dev"},
					},
				},
			},
		},
	)
}

var _ = Describe("KDexFunction Controller", func() {
	Context("When reconciling a KDexFunction", func() {
		const resourceName = "test-function"
		ctx := context.Background()

		AfterEach(func() {
			cleanupResources(namespace)
		})

		It("should fail if hostRef.name is empty", func() {
			resource := &kdexv1alpha1.KDexFunction{
				ObjectMeta: metav1.ObjectMeta{
					Name:      resourceName,
					Namespace: namespace,
				},
				Spec: kdexv1alpha1.KDexFunctionSpec{
					API: kdexv1alpha1.API{
						BasePath: "/v1/api",
						Paths: map[string]kdexv1alpha1.PathItem{
							"/v1/api/test": {},
						},
					},
				},
			}

			err := k8sClient.Create(ctx, resource)
			Expect(err).To(HaveOccurred())
			Expect(err.Error()).To(ContainSubstring("hostRef.name must not be empty"))
		})

		It("should fail if basePath does not match regex", func() {
			resource := &kdexv1alpha1.KDexFunction{
				ObjectMeta: metav1.ObjectMeta{
					Name:      resourceName,
					Namespace: namespace,
				},
				Spec: kdexv1alpha1.KDexFunctionSpec{
					HostRef: corev1.LocalObjectReference{Name: focalHost},
					API: kdexv1alpha1.API{
						BasePath: "/invalid", // only one segment, but regex is ^/\w+/\w+
						Paths: map[string]kdexv1alpha1.PathItem{
							"/invalid/test": {},
						},
					},
				},
			}

			err := k8sClient.Create(ctx, resource)
			Expect(err).To(HaveOccurred())
			Expect(err.Error()).To(ContainSubstring("match"))
		})

		It("should not create with invalid JSON OpenAPI", func() {
			resource := &kdexv1alpha1.KDexFunction{
				ObjectMeta: metav1.ObjectMeta{
					Name:      resourceName,
					Namespace: namespace,
				},
				Spec: kdexv1alpha1.KDexFunctionSpec{
					HostRef: corev1.LocalObjectReference{Name: focalHost},
					Metadata: kdexv1alpha1.KDexFunctionMetadata{
						AutoGenerated: true,
					},
					API: kdexv1alpha1.API{
						BasePath: "/v1/api",
						Paths: map[string]kdexv1alpha1.PathItem{
							"/v1/api/test": {
								Get: &runtime.RawExtension{
									Raw: []byte(`{`),
								},
							},
						},
					},
				},
			}

			err := k8sClient.Create(ctx, resource)
			Expect(err).To(HaveOccurred())
			Expect(err.Error()).To(ContainSubstring("json: error calling MarshalJSON for type *runtime.RawExtension: unexpected end of JSON input"))
		})

		It("becomes OpenAPIValid", func() {
			resource := &kdexv1alpha1.KDexFunction{
				ObjectMeta: metav1.ObjectMeta{
					Name:      resourceName,
					Namespace: namespace,
				},
				Spec: kdexv1alpha1.KDexFunctionSpec{
					HostRef: corev1.LocalObjectReference{Name: focalHost},
					Metadata: kdexv1alpha1.KDexFunctionMetadata{
						AutoGenerated: true,
					},
					API: kdexv1alpha1.API{
						BasePath: "/v1/api",
						Paths: map[string]kdexv1alpha1.PathItem{
							"/v1/api/test": {},
						},
					},
				},
			}

			Expect(k8sClient.Create(ctx, resource)).To(Succeed())

			addOrUpdateInternalHost(
				ctx, k8sClient,
				kdexv1alpha1.KDexInternalHost{
					ObjectMeta: metav1.ObjectMeta{
						Name:      focalHost,
						Namespace: namespace,
					},
					Spec: kdexv1alpha1.KDexInternalHostSpec{
						KDexHostSpec: kdexv1alpha1.KDexHostSpec{
							BrandName:    "KDex Tech",
							DevMode:      true,
							ModulePolicy: kdexv1alpha1.LooseModulePolicy,
							Organization: "KDex Tech Inc.",
							Routing: kdexv1alpha1.Routing{
								Domains: []string{
									"kdex.dev",
								},
							},
						},
					},
				},
			)

			assertResourceReady(
				ctx, k8sClient, focalHost, namespace,
				&kdexv1alpha1.KDexInternalHost{}, true)

			faasAdaptor := &kdexv1alpha1.KDexClusterFaaSAdaptor{
				ObjectMeta: metav1.ObjectMeta{
					Labels: map[string]string{
						"kdex.dev/default": "true",
					},
					Name:      "kdex-default-faas-adaptor-knative",
					Namespace: namespace,
				},
				Spec: kdexv1alpha1.KDexFaaSAdaptorSpec{
					Builders: []kdexv1alpha1.Builder{
						{
							Languages: []string{"go"},
							Name:      "tiny",
							BuilderRef: kdexv1alpha1.KDexObjectReference{
								Kind: "ClusterBuilder",
								Name: "tiny",
							},
						},
					},
					DefaultBuilderGenerator: "tiny/go",
					Deployer: kdexv1alpha1.Deployer{
						Image: "deployer",
					},
					Generators: []kdexv1alpha1.Generator{
						{
							Language: "java",
							Image:    "java",
						},
					},
					Provider: "knative",
				},
			}
			Expect(k8sClient.Create(ctx, faasAdaptor)).To(Succeed())

			Eventually(func(g Gomega) {
				fetched := &kdexv1alpha1.KDexFunction{}
				err := k8sClient.Get(ctx, client.ObjectKey{Name: resource.Name, Namespace: namespace}, fetched)
				g.Expect(err).NotTo(HaveOccurred())
				g.Expect(fetched.Status.State).To(Equal(kdexv1alpha1.KDexFunctionStateOpenAPIValid))
			}, "10s", "1s").Should(Succeed())
		})

		It("becomes BuildValid", func() {
			resource := &kdexv1alpha1.KDexFunction{
				ObjectMeta: metav1.ObjectMeta{
					Name:      resourceName,
					Namespace: namespace,
				},
				Spec: kdexv1alpha1.KDexFunctionSpec{
					HostRef: corev1.LocalObjectReference{Name: focalHost},
					Metadata: kdexv1alpha1.KDexFunctionMetadata{
						AutoGenerated: true,
					},
					API: kdexv1alpha1.API{
						BasePath: "/v1/api",
						Paths: map[string]kdexv1alpha1.PathItem{
							"/v1/api/test": {},
						},
					},
					Origin: kdexv1alpha1.FunctionOrigin{
						Generator: &kdexv1alpha1.Generator{
							Image:    "ghcr.io/kdex-dev/kdex-function-generator-go:latest",
							Language: "go",
						},
					},
				},
			}

			Expect(k8sClient.Create(ctx, resource)).To(Succeed())

			addOrUpdateInternalHost(
				ctx, k8sClient,
				kdexv1alpha1.KDexInternalHost{
					ObjectMeta: metav1.ObjectMeta{
						Name:      focalHost,
						Namespace: namespace,
					},
					Spec: kdexv1alpha1.KDexInternalHostSpec{
						KDexHostSpec: kdexv1alpha1.KDexHostSpec{
							BrandName:    "KDex Tech",
							DevMode:      true,
							ModulePolicy: kdexv1alpha1.LooseModulePolicy,
							Organization: "KDex Tech Inc.",
							Routing: kdexv1alpha1.Routing{
								Domains: []string{
									"kdex.dev",
								},
							},
						},
					},
				},
			)

			assertResourceReady(
				ctx, k8sClient, focalHost, namespace,
				&kdexv1alpha1.KDexInternalHost{}, true)

			faasAdaptor := &kdexv1alpha1.KDexClusterFaaSAdaptor{
				ObjectMeta: metav1.ObjectMeta{
					Labels: map[string]string{
						"kdex.dev/default": "true",
					},
					Name:      "kdex-default-faas-adaptor-knative",
					Namespace: namespace,
				},
				Spec: kdexv1alpha1.KDexFaaSAdaptorSpec{
					Builders: []kdexv1alpha1.Builder{
						{
							Languages: []string{"go"},
							Name:      "tiny",
							BuilderRef: kdexv1alpha1.KDexObjectReference{
								Kind: "ClusterBuilder",
								Name: "tiny",
							},
						},
					},
					DefaultBuilderGenerator: "tiny/go",
					Deployer: kdexv1alpha1.Deployer{
						Image: "deployer",
					},
					Generators: []kdexv1alpha1.Generator{
						{
							Language: "go",
							Image:    "ghcr.io/kdex-dev/kdex-function-generator-go:latest",
						},
					},
					Provider: "knative",
				},
			}
			Expect(k8sClient.Create(ctx, faasAdaptor)).To(Succeed())

			Eventually(func(g Gomega) {
				fetched := &kdexv1alpha1.KDexFunction{}
				err := k8sClient.Get(ctx, client.ObjectKey{Name: resource.Name, Namespace: namespace}, fetched)
				g.Expect(err).NotTo(HaveOccurred())
				g.Expect(
					meta.IsStatusConditionTrue(
						fetched.Status.Conditions,
						string(kdexv1alpha1.ConditionTypeDegraded),
					),
				).To(BeTrue())
				g.Expect(
					meta.IsStatusConditionFalse(
						fetched.Status.Conditions,
						string(kdexv1alpha1.ConditionTypeProgressing),
					),
				).To(BeTrue())
				g.Expect(fetched.Status.State).To(Equal(kdexv1alpha1.KDexFunctionStateBuildValid))
			}, "10s", "1s").Should(Succeed())
		})

		It("becomes SourceAvailable", func() {
			resource := &kdexv1alpha1.KDexFunction{
				ObjectMeta: metav1.ObjectMeta{
					Name:      resourceName,
					Namespace: namespace,
				},
				Spec: kdexv1alpha1.KDexFunctionSpec{
					HostRef: corev1.LocalObjectReference{Name: focalHost},
					Metadata: kdexv1alpha1.KDexFunctionMetadata{
						AutoGenerated: true,
					},
					API: kdexv1alpha1.API{
						BasePath: "/v1/api",
						Paths: map[string]kdexv1alpha1.PathItem{
							"/v1/api/test": {},
						},
					},
					Origin: kdexv1alpha1.FunctionOrigin{
						Source: &kdexv1alpha1.Source{
							Builder: &kdexv1alpha1.Builder{
								Languages: []string{"go"},
								Name:      "tiny",
								BuilderRef: kdexv1alpha1.KDexObjectReference{
									Kind: "ClusterBuilder",
									Name: "tiny",
								},
							},
							Path:       "baz",
							Repository: "foo",
							Revision:   "bar",
						},
					},
				},
			}

			Expect(k8sClient.Create(ctx, resource)).To(Succeed())

			addOrUpdateInternalHost(
				ctx, k8sClient,
				kdexv1alpha1.KDexInternalHost{
					ObjectMeta: metav1.ObjectMeta{
						Name:      focalHost,
						Namespace: namespace,
					},
					Spec: kdexv1alpha1.KDexInternalHostSpec{
						KDexHostSpec: kdexv1alpha1.KDexHostSpec{
							BrandName:    "KDex Tech",
							DevMode:      true,
							ModulePolicy: kdexv1alpha1.LooseModulePolicy,
							Organization: "KDex Tech Inc.",
							Routing: kdexv1alpha1.Routing{
								Domains: []string{
									"kdex.dev",
								},
							},
						},
					},
				},
			)

			assertResourceReady(
				ctx, k8sClient, focalHost, namespace,
				&kdexv1alpha1.KDexInternalHost{}, true)

			faasAdaptor := &kdexv1alpha1.KDexClusterFaaSAdaptor{
				ObjectMeta: metav1.ObjectMeta{
					Labels: map[string]string{
						"kdex.dev/default": "true",
					},
					Name:      "kdex-default-faas-adaptor-knative",
					Namespace: namespace,
				},
				Spec: kdexv1alpha1.KDexFaaSAdaptorSpec{
					Builders: []kdexv1alpha1.Builder{
						{
							Languages: []string{"go"},
							Name:      "tiny",
							BuilderRef: kdexv1alpha1.KDexObjectReference{
								Kind: "ClusterBuilder",
								Name: "tiny",
							},
						},
					},
					DefaultBuilderGenerator: "tiny/go",
					Deployer: kdexv1alpha1.Deployer{
						Image: "deployer",
					},
					Generators: []kdexv1alpha1.Generator{
						{
							Language: "go",
							Image:    "ghcr.io/kdex-dev/kdex-function-generator-go:latest",
						},
					},
					Provider: "knative",
				},
			}
			Expect(k8sClient.Create(ctx, faasAdaptor)).To(Succeed())

			Eventually(func(g Gomega) {
				fetched := &kdexv1alpha1.KDexFunction{}
				err := k8sClient.Get(ctx, client.ObjectKey{Name: resource.Name, Namespace: namespace}, fetched)
				g.Expect(err).NotTo(HaveOccurred())
				g.Expect(
					meta.IsStatusConditionFalse(
						fetched.Status.Conditions,
						string(kdexv1alpha1.ConditionTypeDegraded),
					),
				).To(BeTrue())
				g.Expect(
					meta.IsStatusConditionTrue(
						fetched.Status.Conditions,
						string(kdexv1alpha1.ConditionTypeProgressing),
					),
				).To(BeTrue())
				g.Expect(fetched.Status.State).To(Equal(kdexv1alpha1.KDexFunctionStateSourceAvailable))
			}, "10s", "1s").Should(Succeed())
		})

		It("bypasses SourceAvailable and becomes BuildValid when source.regenerate=true", func() {
			resource := &kdexv1alpha1.KDexFunction{
				ObjectMeta: metav1.ObjectMeta{
					Name:      resourceName,
					Namespace: namespace,
				},
				Spec: kdexv1alpha1.KDexFunctionSpec{
					HostRef: corev1.LocalObjectReference{Name: focalHost},
					Metadata: kdexv1alpha1.KDexFunctionMetadata{
						AutoGenerated: true,
					},
					API: kdexv1alpha1.API{
						BasePath: "/v1/api",
						Paths: map[string]kdexv1alpha1.PathItem{
							"/v1/api/test": {},
						},
					},
					Origin: kdexv1alpha1.FunctionOrigin{
						Source: &kdexv1alpha1.Source{
							Builder: &kdexv1alpha1.Builder{
								Languages: []string{"go"},
								Name:      "tiny",
								BuilderRef: kdexv1alpha1.KDexObjectReference{
									Kind: "ClusterBuilder",
									Name: "tiny",
								},
							},
							Path:       "baz",
							Repository: "foo",
							Revision:   "bar",
							Regenerate: ptr.To(true),
						},
					},
				},
			}

			Expect(k8sClient.Create(ctx, resource)).To(Succeed())

			addOrUpdateInternalHost(
				ctx, k8sClient,
				kdexv1alpha1.KDexInternalHost{
					ObjectMeta: metav1.ObjectMeta{
						Name:      focalHost,
						Namespace: namespace,
					},
					Spec: kdexv1alpha1.KDexInternalHostSpec{
						KDexHostSpec: kdexv1alpha1.KDexHostSpec{
							BrandName:    "KDex Tech",
							DevMode:      true,
							ModulePolicy: kdexv1alpha1.LooseModulePolicy,
							Organization: "KDex Tech Inc.",
							Routing: kdexv1alpha1.Routing{
								Domains: []string{
									"kdex.dev",
								},
							},
						},
					},
				},
			)

			assertResourceReady(
				ctx, k8sClient, focalHost, namespace,
				&kdexv1alpha1.KDexInternalHost{}, true)

			faasAdaptor := &kdexv1alpha1.KDexClusterFaaSAdaptor{
				ObjectMeta: metav1.ObjectMeta{
					Labels: map[string]string{
						"kdex.dev/default": "true",
					},
					Name:      "kdex-default-faas-adaptor-knative",
					Namespace: namespace,
				},
				Spec: kdexv1alpha1.KDexFaaSAdaptorSpec{
					Builders: []kdexv1alpha1.Builder{
						{
							Languages: []string{"go"},
							Name:      "tiny",
							BuilderRef: kdexv1alpha1.KDexObjectReference{
								Kind: "ClusterBuilder",
								Name: "tiny",
							},
						},
					},
					DefaultBuilderGenerator: "tiny/go",
					Deployer: kdexv1alpha1.Deployer{
						Image: "deployer",
					},
					Generators: []kdexv1alpha1.Generator{
						{
							Language: "go",
							Image:    "ghcr.io/kdex-dev/kdex-function-generator-go:latest",
						},
					},
					Provider: "knative",
				},
			}
			Expect(k8sClient.Create(ctx, faasAdaptor)).To(Succeed())

			// With regenerate=true the early-return to SourceAvailable is bypassed;
			// the controller falls through to generator resolution and sets BuildValid.
			// No git secret is present so it degrades there — same observable outcome
			// as the "becomes BuildValid" generator-mode test.
			Eventually(func(g Gomega) {
				fetched := &kdexv1alpha1.KDexFunction{}
				err := k8sClient.Get(ctx, client.ObjectKey{Name: resource.Name, Namespace: namespace}, fetched)
				g.Expect(err).NotTo(HaveOccurred())
				g.Expect(fetched.Status.State).NotTo(Equal(kdexv1alpha1.KDexFunctionStateSourceAvailable),
					"state must not short-circuit to SourceAvailable when regenerate=true")
				g.Expect(fetched.Status.State).To(Equal(kdexv1alpha1.KDexFunctionStateBuildValid))
			}, "10s", "1s").Should(Succeed())
		})

		It("edge-triggers codegen on spec.api change when prior codegen recorded an input hash", func() {
			// Regression for kdex-tech/host-manager#40. Once a function has been
			// codegen-managed (status.attributes["kdex.dev/codegen-input-api-hash"]
			// has been written), a subsequent reconcile where the current spec.api
			// hash differs from the recorded one must enter the codegen branch —
			// regardless of spec.origin.source.regenerate. This eliminates the
			// "regenerate=true stuck on" knob: users edit spec.api, the controller
			// detects the input change automatically.
			//
			// Pre-fix behavior (regenerate=false short-circuits codegen
			// unconditionally): state would jump straight to SourceAvailable.
			// Post-fix: handleBuildValid takes the codegen branch and degrades
			// (no git secret in test) → state stays at BuildValid.
			resource := &kdexv1alpha1.KDexFunction{
				ObjectMeta: metav1.ObjectMeta{Name: resourceName, Namespace: namespace},
				Spec: kdexv1alpha1.KDexFunctionSpec{
					HostRef:  corev1.LocalObjectReference{Name: focalHost},
					Metadata: kdexv1alpha1.KDexFunctionMetadata{AutoGenerated: true},
					API: kdexv1alpha1.API{
						BasePath: "/v1/api",
						Paths:    map[string]kdexv1alpha1.PathItem{"/v1/api/test": {}},
					},
					Origin: kdexv1alpha1.FunctionOrigin{
						Source: &kdexv1alpha1.Source{
							Builder: &kdexv1alpha1.Builder{
								Languages: []string{"go"},
								Name:      "tiny",
								BuilderRef: kdexv1alpha1.KDexObjectReference{
									Kind: "ClusterBuilder",
									Name: "tiny",
								},
							},
							Path:       "baz",
							Repository: "foo",
							Revision:   "bar",
							// Regenerate intentionally omitted (= false).
						},
					},
				},
			}
			Expect(k8sClient.Create(ctx, resource)).To(Succeed())

			ensureFocalHost(ctx, namespace, focalHost)
			assertResourceReady(ctx, k8sClient, focalHost, namespace, &kdexv1alpha1.KDexInternalHost{}, true)

			faasAdaptor := &kdexv1alpha1.KDexClusterFaaSAdaptor{
				ObjectMeta: metav1.ObjectMeta{
					Labels:    map[string]string{"kdex.dev/default": "true"},
					Name:      "kdex-default-faas-adaptor-knative",
					Namespace: namespace,
				},
				Spec: kdexv1alpha1.KDexFaaSAdaptorSpec{
					Builders: []kdexv1alpha1.Builder{{
						Languages:  []string{"go"},
						Name:       "tiny",
						BuilderRef: kdexv1alpha1.KDexObjectReference{Kind: "ClusterBuilder", Name: "tiny"},
					}},
					DefaultBuilderGenerator: "tiny/go",
					Deployer:                kdexv1alpha1.Deployer{Image: "deployer"},
					Generators: []kdexv1alpha1.Generator{{
						Language: "go",
						Image:    "ghcr.io/kdex-dev/kdex-function-generator-go:latest",
					}},
					Provider: "knative",
				},
			}
			Expect(k8sClient.Create(ctx, faasAdaptor)).To(Succeed())

			// First reconcile reaches SourceAvailable via the regenerate=false
			// short-circuit (today's behavior — backwards-compatible for
			// never-codegen'd functions where no input hash is recorded).
			Eventually(func(g Gomega) {
				fetched := &kdexv1alpha1.KDexFunction{}
				g.Expect(k8sClient.Get(ctx, client.ObjectKey{Name: resource.Name, Namespace: namespace}, fetched)).To(Succeed())
				g.Expect(fetched.Status.State).To(Equal(kdexv1alpha1.KDexFunctionStateSourceAvailable))
			}, "10s", "1s").Should(Succeed())

			// Now simulate "this function has been codegen-managed before, and
			// the input hash recorded then doesn't match the current spec.api."
			// Pre-set a stale hash + reset state to BuildValid to re-enter
			// handleBuildValid with edgeMode=true.
			fetched := &kdexv1alpha1.KDexFunction{}
			Expect(k8sClient.Get(ctx, client.ObjectKey{Name: resource.Name, Namespace: namespace}, fetched)).To(Succeed())
			patch := client.MergeFrom(fetched.DeepCopy())
			if fetched.Status.Attributes == nil {
				fetched.Status.Attributes = map[string]string{}
			}
			fetched.Status.Attributes["kdex.dev/codegen-input-api-hash"] = "stale-hash-from-prior-codegen"
			fetched.Status.Attributes["kdex.dev/codegen-input-generator"] = "ghcr.io/kdex-dev/kdex-function-generator-go:latest"
			fetched.Status.State = kdexv1alpha1.KDexFunctionStateBuildValid
			Expect(k8sClient.Status().Patch(ctx, fetched, patch)).To(Succeed())

			// Post-fix: handleBuildValid sees observed hash != current hash and
			// enters the codegen branch. Without a git secret in the test
			// environment, codegen degrades — state stays at BuildValid and
			// Degraded becomes True. This is the observable signal that
			// codegen was triggered by the input-hash change, not by the
			// regenerate flag (which is false).
			Eventually(func(g Gomega) {
				f := &kdexv1alpha1.KDexFunction{}
				g.Expect(k8sClient.Get(ctx, client.ObjectKey{Name: resource.Name, Namespace: namespace}, f)).To(Succeed())
				g.Expect(f.Status.State).To(Equal(kdexv1alpha1.KDexFunctionStateBuildValid),
					"edge-trigger must keep state at BuildValid when input hash differs (codegen needs to run)")
				g.Expect(meta.IsStatusConditionTrue(f.Status.Conditions, string(kdexv1alpha1.ConditionTypeDegraded))).To(BeTrue(),
					"Degraded=True confirms the codegen branch was entered (git secret absent in test)")
			}, "10s", "1s").Should(Succeed())
		})

		It("edge-triggers codegen on spec.api change while function is Ready", func() {
			// Regression for kdex-tech/host-manager#41. The edge-trigger check at
			// handleBuildValid only runs while state==BuildValid. A function that
			// reached Ready then had its spec.api edited would reconcile through
			// handleReady — which calls deployer.Observe() but doesn't compare
			// codegen inputs — so the input change silently stuck.
			//
			// Fix: Reconcile() regresses Ready→BuildValid when the live api-hash
			// differs from the recorded one (mirrors the kpack-SHA regression
			// already present for kdex-tech/host-manager#38). Once at BuildValid,
			// the existing edge-trigger path (handleBuildValid) takes over.
			resource := &kdexv1alpha1.KDexFunction{
				ObjectMeta: metav1.ObjectMeta{Name: resourceName, Namespace: namespace},
				Spec: kdexv1alpha1.KDexFunctionSpec{
					HostRef:  corev1.LocalObjectReference{Name: focalHost},
					Metadata: kdexv1alpha1.KDexFunctionMetadata{AutoGenerated: true},
					API: kdexv1alpha1.API{
						BasePath: "/v1/api",
						Paths:    map[string]kdexv1alpha1.PathItem{"/v1/api/test": {}},
					},
					Origin: kdexv1alpha1.FunctionOrigin{
						Source: &kdexv1alpha1.Source{
							Builder: &kdexv1alpha1.Builder{
								Languages: []string{"go"},
								Name:      "tiny",
								BuilderRef: kdexv1alpha1.KDexObjectReference{
									Kind: "ClusterBuilder",
									Name: "tiny",
								},
							},
							Path:       "baz",
							Repository: "foo",
							Revision:   "bar",
						},
					},
				},
			}
			Expect(k8sClient.Create(ctx, resource)).To(Succeed())

			ensureFocalHost(ctx, namespace, focalHost)
			assertResourceReady(ctx, k8sClient, focalHost, namespace, &kdexv1alpha1.KDexInternalHost{}, true)

			faasAdaptor := &kdexv1alpha1.KDexClusterFaaSAdaptor{
				ObjectMeta: metav1.ObjectMeta{
					Labels:    map[string]string{"kdex.dev/default": "true"},
					Name:      "kdex-default-faas-adaptor-knative",
					Namespace: namespace,
				},
				Spec: kdexv1alpha1.KDexFaaSAdaptorSpec{
					Builders: []kdexv1alpha1.Builder{{
						Languages:  []string{"go"},
						Name:       "tiny",
						BuilderRef: kdexv1alpha1.KDexObjectReference{Kind: "ClusterBuilder", Name: "tiny"},
					}},
					DefaultBuilderGenerator: "tiny/go",
					Deployer:                kdexv1alpha1.Deployer{Image: "deployer"},
					Generators: []kdexv1alpha1.Generator{{
						Language: "go",
						Image:    "ghcr.io/kdex-dev/kdex-function-generator-go:latest",
					}},
					Provider: "knative",
				},
			}
			Expect(k8sClient.Create(ctx, faasAdaptor)).To(Succeed())

			// Drive the controller to SourceAvailable on the regenerate=false
			// short-circuit (no recorded input hash yet).
			Eventually(func(g Gomega) {
				fetched := &kdexv1alpha1.KDexFunction{}
				g.Expect(k8sClient.Get(ctx, client.ObjectKey{Name: resource.Name, Namespace: namespace}, fetched)).To(Succeed())
				g.Expect(fetched.Status.State).To(Equal(kdexv1alpha1.KDexFunctionStateSourceAvailable))
			}, "10s", "1s").Should(Succeed())

			// Simulate "this function has been codegen-managed before, recorded
			// inputs, and reached Ready" — then a subsequent spec.api edit drifted
			// the live hash from the recorded one. Force state to Ready with a
			// stale hash. Without the Reconcile-level regression, handleReady
			// would just call deployer.Observe() and the input drift would never
			// surface.
			fetched := &kdexv1alpha1.KDexFunction{}
			Expect(k8sClient.Get(ctx, client.ObjectKey{Name: resource.Name, Namespace: namespace}, fetched)).To(Succeed())
			patch := client.MergeFrom(fetched.DeepCopy())
			if fetched.Status.Attributes == nil {
				fetched.Status.Attributes = map[string]string{}
			}
			fetched.Status.Attributes["kdex.dev/codegen-input-api-hash"] = "stale-hash-from-prior-codegen"
			fetched.Status.Attributes["kdex.dev/codegen-input-generator"] = "ghcr.io/kdex-dev/kdex-function-generator-go:latest"
			fetched.Status.Executable = &kdexv1alpha1.Executable{Image: "old-image"}
			fetched.Status.State = kdexv1alpha1.KDexFunctionStateReady
			Expect(k8sClient.Status().Patch(ctx, fetched, patch)).To(Succeed())

			// Post-fix: Reconcile regresses Ready→BuildValid (hash mismatch),
			// handleBuildValid enters the codegen branch, degrades on missing
			// git secret, ends at BuildValid + Degraded=True. Same observable
			// signal as the BuildValid-entry edge-trigger test above.
			Eventually(func(g Gomega) {
				f := &kdexv1alpha1.KDexFunction{}
				g.Expect(k8sClient.Get(ctx, client.ObjectKey{Name: resource.Name, Namespace: namespace}, f)).To(Succeed())
				g.Expect(f.Status.State).To(Equal(kdexv1alpha1.KDexFunctionStateBuildValid),
					"Reconcile must regress Ready→BuildValid when codegen inputs drifted")
				g.Expect(meta.IsStatusConditionTrue(f.Status.Conditions, string(kdexv1alpha1.ConditionTypeDegraded))).To(BeTrue(),
					"Degraded=True confirms codegen ran post-regression")
			}, "10s", "1s").Should(Succeed())
		})

		It("forwards spec.origin.source.builder.serviceAccountName to the kpack Image", func() {
			const customBuildSA = "custom-build-sa"

			resource := &kdexv1alpha1.KDexFunction{
				ObjectMeta: metav1.ObjectMeta{
					Name:      resourceName,
					Namespace: namespace,
				},
				Spec: kdexv1alpha1.KDexFunctionSpec{
					HostRef: corev1.LocalObjectReference{Name: focalHost},
					Metadata: kdexv1alpha1.KDexFunctionMetadata{
						AutoGenerated: true,
					},
					API: kdexv1alpha1.API{
						BasePath: "/v1/api",
						Paths: map[string]kdexv1alpha1.PathItem{
							"/v1/api/test": {},
						},
					},
					Origin: kdexv1alpha1.FunctionOrigin{
						Source: &kdexv1alpha1.Source{
							Builder: &kdexv1alpha1.Builder{
								Languages: []string{"go"},
								Name:      "tiny",
								BuilderRef: kdexv1alpha1.KDexObjectReference{
									Kind: "ClusterBuilder",
									Name: "tiny",
								},
								ServiceAccountName: customBuildSA,
							},
							Path:       "baz",
							Repository: "foo",
							Revision:   "bar",
						},
					},
				},
			}

			Expect(k8sClient.Create(ctx, resource)).To(Succeed())

			addOrUpdateInternalHost(
				ctx, k8sClient,
				kdexv1alpha1.KDexInternalHost{
					ObjectMeta: metav1.ObjectMeta{
						Name:      focalHost,
						Namespace: namespace,
					},
					Spec: kdexv1alpha1.KDexInternalHostSpec{
						KDexHostSpec: kdexv1alpha1.KDexHostSpec{
							BrandName:    "KDex Tech",
							DevMode:      true,
							ModulePolicy: kdexv1alpha1.LooseModulePolicy,
							Organization: "KDex Tech Inc.",
							Routing: kdexv1alpha1.Routing{
								Domains: []string{
									"kdex.dev",
								},
							},
						},
					},
				},
			)

			assertResourceReady(
				ctx, k8sClient, focalHost, namespace,
				&kdexv1alpha1.KDexInternalHost{}, true)

			faasAdaptor := &kdexv1alpha1.KDexClusterFaaSAdaptor{
				ObjectMeta: metav1.ObjectMeta{
					Labels: map[string]string{
						"kdex.dev/default": "true",
					},
					Name:      "kdex-default-faas-adaptor-knative",
					Namespace: namespace,
				},
				Spec: kdexv1alpha1.KDexFaaSAdaptorSpec{
					Builders: []kdexv1alpha1.Builder{
						{
							Languages: []string{"go"},
							Name:      "tiny",
							BuilderRef: kdexv1alpha1.KDexObjectReference{
								Kind: "ClusterBuilder",
								Name: "tiny",
							},
						},
					},
					DefaultBuilderGenerator: "tiny/go",
					Deployer: kdexv1alpha1.Deployer{
						Image: "deployer",
					},
					Generators: []kdexv1alpha1.Generator{
						{
							Language: "go",
							Image:    "ghcr.io/kdex-dev/kdex-function-generator-go:latest",
						},
					},
					Provider: "knative",
				},
			}
			Expect(k8sClient.Create(ctx, faasAdaptor)).To(Succeed())

			kImageName := focalHost + "-" + resource.Name
			Eventually(func(g Gomega) {
				kImage := &unstructured.Unstructured{}
				kImage.SetGroupVersionKind(internal.KPackImageGVK)
				err := k8sClient.Get(ctx, client.ObjectKey{Name: kImageName, Namespace: namespace}, kImage)
				g.Expect(err).NotTo(HaveOccurred())
				sa, found, err := unstructured.NestedString(kImage.Object, "spec", "serviceAccountName")
				g.Expect(err).NotTo(HaveOccurred())
				g.Expect(found).To(BeTrue())
				g.Expect(sa).To(Equal(customBuildSA))

				// successBuildHistoryLimit + failedBuildHistoryLimit explicit
				// so kpack's webhook can't re-default them to 10. See
				// internal/build/build.go for the rationale.
				success, found, err := unstructured.NestedInt64(kImage.Object, "spec", "successBuildHistoryLimit")
				g.Expect(err).NotTo(HaveOccurred())
				g.Expect(found).To(BeTrue())
				g.Expect(success).To(Equal(int64(3)))
				failed, found, err := unstructured.NestedInt64(kImage.Object, "spec", "failedBuildHistoryLimit")
				g.Expect(err).NotTo(HaveOccurred())
				g.Expect(found).To(BeTrue())
				g.Expect(failed).To(Equal(int64(3)))
			}, "10s", "1s").Should(Succeed())
		})

		It("forwards spec.origin.source.builder.{Tolerations,NodeSelector,Resources} to the kpack Image", func() {
			resource := &kdexv1alpha1.KDexFunction{
				ObjectMeta: metav1.ObjectMeta{
					Name:      resourceName,
					Namespace: namespace,
				},
				Spec: kdexv1alpha1.KDexFunctionSpec{
					HostRef: corev1.LocalObjectReference{Name: focalHost},
					Metadata: kdexv1alpha1.KDexFunctionMetadata{
						AutoGenerated: true,
					},
					API: kdexv1alpha1.API{
						BasePath: "/v1/api",
						Paths: map[string]kdexv1alpha1.PathItem{
							"/v1/api/test": {},
						},
					},
					Origin: kdexv1alpha1.FunctionOrigin{
						Source: &kdexv1alpha1.Source{
							Builder: &kdexv1alpha1.Builder{
								Languages: []string{"go"},
								Name:      "tiny",
								BuilderRef: kdexv1alpha1.KDexObjectReference{
									Kind: "ClusterBuilder",
									Name: "tiny",
								},
								Tolerations: []corev1.Toleration{{
									Key:      "cloud.google.com/gke-spot",
									Operator: corev1.TolerationOpEqual,
									Value:    "true",
									Effect:   corev1.TaintEffectNoSchedule,
								}},
								NodeSelector: map[string]string{
									"component": "kpack-build",
								},
							},
							Path:       "baz",
							Repository: "foo",
							Revision:   "bar",
						},
					},
				},
			}
			Expect(k8sClient.Create(ctx, resource)).To(Succeed())

			addOrUpdateInternalHost(
				ctx, k8sClient,
				kdexv1alpha1.KDexInternalHost{
					ObjectMeta: metav1.ObjectMeta{Name: focalHost, Namespace: namespace},
					Spec: kdexv1alpha1.KDexInternalHostSpec{
						KDexHostSpec: kdexv1alpha1.KDexHostSpec{
							BrandName: "KDex Tech", DevMode: true,
							ModulePolicy: kdexv1alpha1.LooseModulePolicy,
							Organization: "KDex Tech Inc.",
							Routing:      kdexv1alpha1.Routing{Domains: []string{"kdex.dev"}},
						},
					},
				},
			)
			assertResourceReady(ctx, k8sClient, focalHost, namespace, &kdexv1alpha1.KDexInternalHost{}, true)

			faasAdaptor := &kdexv1alpha1.KDexClusterFaaSAdaptor{
				ObjectMeta: metav1.ObjectMeta{
					Labels:    map[string]string{"kdex.dev/default": "true"},
					Name:      "kdex-default-faas-adaptor-knative",
					Namespace: namespace,
				},
				Spec: kdexv1alpha1.KDexFaaSAdaptorSpec{
					Builders: []kdexv1alpha1.Builder{{
						Languages:  []string{"go"},
						Name:       "tiny",
						BuilderRef: kdexv1alpha1.KDexObjectReference{Kind: "ClusterBuilder", Name: "tiny"},
					}},
					DefaultBuilderGenerator: "tiny/go",
					Deployer:                kdexv1alpha1.Deployer{Image: "deployer"},
					Generators: []kdexv1alpha1.Generator{{
						Language: "go",
						Image:    "ghcr.io/kdex-dev/kdex-function-generator-go:latest",
					}},
					Provider: "knative",
				},
			}
			Expect(k8sClient.Create(ctx, faasAdaptor)).To(Succeed())

			kImageName := focalHost + "-" + resource.Name
			Eventually(func(g Gomega) {
				kImage := &unstructured.Unstructured{}
				kImage.SetGroupVersionKind(internal.KPackImageGVK)
				err := k8sClient.Get(ctx, client.ObjectKey{Name: kImageName, Namespace: namespace}, kImage)
				g.Expect(err).NotTo(HaveOccurred())

				tols, found, err := unstructured.NestedSlice(kImage.Object, "spec", "build", "tolerations")
				g.Expect(err).NotTo(HaveOccurred())
				g.Expect(found).To(BeTrue())
				g.Expect(tols).To(HaveLen(1))
				tol := tols[0].(map[string]any)
				g.Expect(tol["key"]).To(Equal("cloud.google.com/gke-spot"))
				g.Expect(tol["value"]).To(Equal("true"))
				g.Expect(tol["effect"]).To(Equal("NoSchedule"))

				ns, found, err := unstructured.NestedStringMap(kImage.Object, "spec", "build", "nodeSelector")
				g.Expect(err).NotTo(HaveOccurred())
				g.Expect(found).To(BeTrue())
				g.Expect(ns).To(HaveKeyWithValue("component", "kpack-build"))
			}, "10s", "1s").Should(Succeed())
		})

		It("falls back to FaaSAdaptor.DefaultBuilderGenerator when Source.Builder is nil", func() {
			// Source with NO Builder set — simulates the generator-mode happy path
			// where the codegen Job populates Status.Source.{Repository,Revision,Path}
			// but not Builder.
			resource := &kdexv1alpha1.KDexFunction{
				ObjectMeta: metav1.ObjectMeta{
					Name:      resourceName,
					Namespace: namespace,
				},
				Spec: kdexv1alpha1.KDexFunctionSpec{
					HostRef: corev1.LocalObjectReference{Name: focalHost},
					Metadata: kdexv1alpha1.KDexFunctionMetadata{
						AutoGenerated: true,
					},
					API: kdexv1alpha1.API{
						BasePath: "/v1/api",
						Paths: map[string]kdexv1alpha1.PathItem{
							"/v1/api/test": {},
						},
					},
					Origin: kdexv1alpha1.FunctionOrigin{
						Source: &kdexv1alpha1.Source{
							// Builder intentionally omitted.
							Path:       "baz",
							Repository: "foo",
							Revision:   "bar",
						},
					},
				},
			}
			Expect(k8sClient.Create(ctx, resource)).To(Succeed())

			addOrUpdateInternalHost(
				ctx, k8sClient,
				kdexv1alpha1.KDexInternalHost{
					ObjectMeta: metav1.ObjectMeta{Name: focalHost, Namespace: namespace},
					Spec: kdexv1alpha1.KDexInternalHostSpec{
						KDexHostSpec: kdexv1alpha1.KDexHostSpec{
							BrandName: "KDex Tech", DevMode: true,
							ModulePolicy: kdexv1alpha1.LooseModulePolicy,
							Organization: "KDex Tech Inc.",
							Routing:      kdexv1alpha1.Routing{Domains: []string{"kdex.dev"}},
						},
					},
				},
			)
			assertResourceReady(ctx, k8sClient, focalHost, namespace, &kdexv1alpha1.KDexInternalHost{}, true)

			faasAdaptor := &kdexv1alpha1.KDexClusterFaaSAdaptor{
				ObjectMeta: metav1.ObjectMeta{
					Labels:    map[string]string{"kdex.dev/default": "true"},
					Name:      "kdex-default-faas-adaptor-knative",
					Namespace: namespace,
				},
				Spec: kdexv1alpha1.KDexFaaSAdaptorSpec{
					Builders: []kdexv1alpha1.Builder{{
						Languages:  []string{"go"},
						Name:       "tiny",
						BuilderRef: kdexv1alpha1.KDexObjectReference{Kind: "ClusterBuilder", Name: "tiny-fallback"},
					}},
					DefaultBuilderGenerator: "tiny/go",
					Deployer:                kdexv1alpha1.Deployer{Image: "deployer"},
					Generators: []kdexv1alpha1.Generator{{
						Language: "go",
						Image:    "ghcr.io/kdex-dev/kdex-function-generator-go:latest",
					}},
					Provider: "knative",
				},
			}
			Expect(k8sClient.Create(ctx, faasAdaptor)).To(Succeed())

			kImageName := focalHost + "-" + resource.Name
			Eventually(func(g Gomega) {
				kImage := &unstructured.Unstructured{}
				kImage.SetGroupVersionKind(internal.KPackImageGVK)
				err := k8sClient.Get(ctx, client.ObjectKey{Name: kImageName, Namespace: namespace}, kImage)
				g.Expect(err).NotTo(HaveOccurred())
				name, found, err := unstructured.NestedString(kImage.Object, "spec", "builder", "name")
				g.Expect(err).NotTo(HaveOccurred())
				g.Expect(found).To(BeTrue())
				g.Expect(name).To(Equal("tiny-fallback"))
			}, "10s", "1s").Should(Succeed())
		})

		It("pins kpack Image to status.source.revision (SHA) over spec.origin.source.revision (branch)", func() {
			// Regression for kdex-tech/host-manager#38. When the codegen Job (or
			// any other path) populates status.source.revision with a concrete
			// SHA, the kpack Image must use that SHA — not the branch ref from
			// spec.origin.source.revision. Otherwise kpack's SourceResolver
			// stays in ActivePolling mode and emits a COMMIT-reason Build on
			// every unrelated push to the branch (monorepo "noisy neighbor").
			const headSHA = "a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0"

			resource := &kdexv1alpha1.KDexFunction{
				ObjectMeta: metav1.ObjectMeta{
					Name:      resourceName,
					Namespace: namespace,
				},
				Spec: kdexv1alpha1.KDexFunctionSpec{
					HostRef: corev1.LocalObjectReference{Name: focalHost},
					Metadata: kdexv1alpha1.KDexFunctionMetadata{
						AutoGenerated: true,
					},
					API: kdexv1alpha1.API{
						BasePath: "/v1/api",
						Paths: map[string]kdexv1alpha1.PathItem{
							"/v1/api/test": {},
						},
					},
					Origin: kdexv1alpha1.FunctionOrigin{
						Source: &kdexv1alpha1.Source{
							Builder: &kdexv1alpha1.Builder{
								Languages: []string{"go"},
								Name:      "tiny",
								BuilderRef: kdexv1alpha1.KDexObjectReference{
									Kind: "ClusterBuilder",
									Name: "tiny",
								},
							},
							Path:       "./functions/foo",
							Repository: "https://example.com/monorepo",
							Revision:   "main",
						},
					},
				},
			}
			Expect(k8sClient.Create(ctx, resource)).To(Succeed())

			ensureFocalHost(ctx, namespace, focalHost)
			assertResourceReady(ctx, k8sClient, focalHost, namespace, &kdexv1alpha1.KDexInternalHost{}, true)

			faasAdaptor := &kdexv1alpha1.KDexClusterFaaSAdaptor{
				ObjectMeta: metav1.ObjectMeta{
					Labels:    map[string]string{"kdex.dev/default": "true"},
					Name:      "kdex-default-faas-adaptor-knative",
					Namespace: namespace,
				},
				Spec: kdexv1alpha1.KDexFaaSAdaptorSpec{
					Builders: []kdexv1alpha1.Builder{{
						Languages:  []string{"go"},
						Name:       "tiny",
						BuilderRef: kdexv1alpha1.KDexObjectReference{Kind: "ClusterBuilder", Name: "tiny"},
					}},
					DefaultBuilderGenerator: "tiny/go",
					Deployer:                kdexv1alpha1.Deployer{Image: "deployer"},
					Generators: []kdexv1alpha1.Generator{{
						Language: "go",
						Image:    "ghcr.io/kdex-dev/kdex-function-generator-go:latest",
					}},
					Provider: "knative",
				},
			}
			Expect(k8sClient.Create(ctx, faasAdaptor)).To(Succeed())

			// Wait for the initial kpack Image to be created. revision should
			// be "main" at this point because nothing has populated status yet.
			kImageName := focalHost + "-" + resource.Name
			Eventually(func(g Gomega) {
				kImage := &unstructured.Unstructured{}
				kImage.SetGroupVersionKind(internal.KPackImageGVK)
				err := k8sClient.Get(ctx, client.ObjectKey{Name: kImageName, Namespace: namespace}, kImage)
				g.Expect(err).NotTo(HaveOccurred())
				rev, found, err := unstructured.NestedString(kImage.Object, "spec", "source", "git", "revision")
				g.Expect(err).NotTo(HaveOccurred())
				g.Expect(found).To(BeTrue())
				g.Expect(rev).To(Equal("main"))
			}, "10s", "1s").Should(Succeed())

			// Simulate the codegen Job completing and writing a SHA to
			// status.source.revision (the patch_source_status step in
			// kdex-cli-tools is the real-world producer of this value).
			// Re-fetch the resource first so we have an up-to-date
			// ResourceVersion for the status patch.
			fetched := &kdexv1alpha1.KDexFunction{}
			Expect(k8sClient.Get(ctx, client.ObjectKey{Name: resource.Name, Namespace: namespace}, fetched)).To(Succeed())
			patch := client.MergeFrom(fetched.DeepCopy())
			fetched.Status.Source = &kdexv1alpha1.Source{
				Repository: "https://example.com/monorepo",
				Revision:   headSHA,
				Path:       "./functions/foo",
			}
			Expect(k8sClient.Status().Patch(ctx, fetched, patch)).To(Succeed())

			// Reconcile must (a) not clobber the SHA back to "main" on the
			// next pass (fix 3a in #38) and (b) propagate the SHA into the
			// kpack Image's spec.source.git.revision (fix 3b in #38).
			Eventually(func(g Gomega) {
				kImage := &unstructured.Unstructured{}
				kImage.SetGroupVersionKind(internal.KPackImageGVK)
				err := k8sClient.Get(ctx, client.ObjectKey{Name: kImageName, Namespace: namespace}, kImage)
				g.Expect(err).NotTo(HaveOccurred())
				rev, found, err := unstructured.NestedString(kImage.Object, "spec", "source", "git", "revision")
				g.Expect(err).NotTo(HaveOccurred())
				g.Expect(found).To(BeTrue())
				g.Expect(rev).To(Equal(headSHA),
					"kpack Image revision must follow status.source.revision (codegen-resolved SHA), "+
						"not spec.origin.source.revision (the source branch)")

				// status.source.revision must also still be the SHA — the
				// reconciler must not have rewritten it back to "main".
				fn := &kdexv1alpha1.KDexFunction{}
				g.Expect(k8sClient.Get(ctx, client.ObjectKey{Name: resource.Name, Namespace: namespace}, fn)).To(Succeed())
				g.Expect(fn.Status.Source).NotTo(BeNil())
				g.Expect(fn.Status.Source.Revision).To(Equal(headSHA))
			}, "15s", "1s").Should(Succeed())
		})

		It("becomes ExecutableAvailable", func() {
			resource := &kdexv1alpha1.KDexFunction{
				ObjectMeta: metav1.ObjectMeta{
					Name:      resourceName,
					Namespace: namespace,
				},
				Spec: kdexv1alpha1.KDexFunctionSpec{
					HostRef: corev1.LocalObjectReference{Name: focalHost},
					Metadata: kdexv1alpha1.KDexFunctionMetadata{
						AutoGenerated: true,
					},
					API: kdexv1alpha1.API{
						BasePath: "/v1/api",
						Paths: map[string]kdexv1alpha1.PathItem{
							"/v1/api/test": {},
						},
					},
					Origin: kdexv1alpha1.FunctionOrigin{
						Executable: &kdexv1alpha1.Executable{
							Image: "foo",
						},
					},
				},
			}

			Expect(k8sClient.Create(ctx, resource)).To(Succeed())

			addOrUpdateInternalHost(
				ctx, k8sClient,
				kdexv1alpha1.KDexInternalHost{
					ObjectMeta: metav1.ObjectMeta{
						Name:      focalHost,
						Namespace: namespace,
					},
					Spec: kdexv1alpha1.KDexInternalHostSpec{
						KDexHostSpec: kdexv1alpha1.KDexHostSpec{
							BrandName:    "KDex Tech",
							DevMode:      true,
							ModulePolicy: kdexv1alpha1.LooseModulePolicy,
							Organization: "KDex Tech Inc.",
							Routing: kdexv1alpha1.Routing{
								Domains: []string{
									"kdex.dev",
								},
							},
						},
					},
				},
			)

			assertResourceReady(
				ctx, k8sClient, focalHost, namespace,
				&kdexv1alpha1.KDexInternalHost{}, true)

			faasAdaptor := &kdexv1alpha1.KDexClusterFaaSAdaptor{
				ObjectMeta: metav1.ObjectMeta{
					Labels: map[string]string{
						"kdex.dev/default": "true",
					},
					Name:      "kdex-default-faas-adaptor-knative",
					Namespace: namespace,
				},
				Spec: kdexv1alpha1.KDexFaaSAdaptorSpec{
					Builders: []kdexv1alpha1.Builder{
						{
							Languages: []string{"go"},
							Name:      "tiny",
							BuilderRef: kdexv1alpha1.KDexObjectReference{
								Kind: "ClusterBuilder",
								Name: "tiny",
							},
						},
					},
					DefaultBuilderGenerator: "tiny/go",
					Deployer: kdexv1alpha1.Deployer{
						Image: "deployer",
					},
					Generators: []kdexv1alpha1.Generator{
						{
							Language: "go",
							Image:    "ghcr.io/kdex-dev/kdex-function-generator-go:latest",
						},
					},
					Provider: "knative",
				},
			}
			Expect(k8sClient.Create(ctx, faasAdaptor)).To(Succeed())

			Eventually(func(g Gomega) {
				fetched := &kdexv1alpha1.KDexFunction{}
				err := k8sClient.Get(ctx, client.ObjectKey{Name: resource.Name, Namespace: namespace}, fetched)
				g.Expect(err).NotTo(HaveOccurred())
				g.Expect(fetched.Status.State).To(Equal(kdexv1alpha1.KDexFunctionStateExecutableAvailable))
				// Regression: state=ExecutableAvailable must imply
				// status.executable is populated so the deployer Job
				// path (which reads Status.Executable, not Spec.Origin)
				// can resolve the image. Bug filed as kdex-tech/
				// host-manager#24 — handleOpenAPIValid + handleBuildValid
				// used to short-circuit the state transition without
				// copying Spec.Origin.Executable into Status.Executable.
				g.Expect(fetched.Status.Executable).NotTo(BeNil(),
					"Status.Executable must be populated when state=ExecutableAvailable")
				g.Expect(fetched.Status.Executable.Image).To(Equal("foo"))
			}, "10s", "1s").Should(Succeed())
		})

		It("becomes FunctionDeployed", func() {
			Skip("Not ready yet")

			resource := &kdexv1alpha1.KDexFunction{
				ObjectMeta: metav1.ObjectMeta{
					Name:      resourceName,
					Namespace: namespace,
				},
				Spec: kdexv1alpha1.KDexFunctionSpec{
					HostRef: corev1.LocalObjectReference{Name: focalHost},
					Metadata: kdexv1alpha1.KDexFunctionMetadata{
						AutoGenerated: true,
					},
					API: kdexv1alpha1.API{
						BasePath: "/v1/api",
						Paths: map[string]kdexv1alpha1.PathItem{
							"/v1/api/test": {},
						},
					},
				},
			}

			Expect(k8sClient.Create(ctx, resource)).To(Succeed())

			addOrUpdateInternalHost(
				ctx, k8sClient,
				kdexv1alpha1.KDexInternalHost{
					ObjectMeta: metav1.ObjectMeta{
						Name:      focalHost,
						Namespace: namespace,
					},
					Spec: kdexv1alpha1.KDexInternalHostSpec{
						KDexHostSpec: kdexv1alpha1.KDexHostSpec{
							BrandName:    "KDex Tech",
							DevMode:      true,
							ModulePolicy: kdexv1alpha1.LooseModulePolicy,
							Organization: "KDex Tech Inc.",
							Routing: kdexv1alpha1.Routing{
								Domains: []string{
									"kdex.dev",
								},
							},
						},
					},
				},
			)

			assertResourceReady(
				ctx, k8sClient, focalHost, namespace,
				&kdexv1alpha1.KDexInternalHost{}, true)

			faasAdaptor := &kdexv1alpha1.KDexClusterFaaSAdaptor{
				ObjectMeta: metav1.ObjectMeta{
					Labels: map[string]string{
						"kdex.dev/default": "true",
					},
					Name:      "kdex-default-faas-adaptor-knative",
					Namespace: namespace,
				},
				Spec: kdexv1alpha1.KDexFaaSAdaptorSpec{
					Builders: []kdexv1alpha1.Builder{
						{
							Languages: []string{"go"},
							Name:      "tiny",
							BuilderRef: kdexv1alpha1.KDexObjectReference{
								Kind: "ClusterBuilder",
								Name: "tiny",
							},
						},
					},
					DefaultBuilderGenerator: "tiny/go",
					Deployer: kdexv1alpha1.Deployer{
						Image: "deployer",
					},
					Generators: []kdexv1alpha1.Generator{
						{
							Language: "go",
							Image:    "ghcr.io/kdex-dev/kdex-function-generator-go:latest",
						},
					},
					Provider: "knative",
				},
			}
			Expect(k8sClient.Create(ctx, faasAdaptor)).To(Succeed())

			patch := client.MergeFrom(resource.DeepCopy())
			resource.Status.URL = "https://foo.bar"
			resource.Status.ObservedGeneration = resource.Generation
			Expect(k8sClient.Status().Patch(ctx, resource, patch)).To(Succeed())

			Eventually(func(g Gomega) {
				fetched := &kdexv1alpha1.KDexFunction{}
				err := k8sClient.Get(ctx, client.ObjectKey{Name: resource.Name, Namespace: namespace}, fetched)
				g.Expect(err).NotTo(HaveOccurred())
				g.Expect(fetched.Status.State).To(Equal(kdexv1alpha1.KDexFunctionStateFunctionDeployed))
				g.Expect(
					meta.IsStatusConditionFalse(
						fetched.Status.Conditions,
						string(kdexv1alpha1.ConditionTypeDegraded),
					),
				).To(BeTrue())
				g.Expect(
					meta.IsStatusConditionFalse(
						fetched.Status.Conditions,
						string(kdexv1alpha1.ConditionTypeProgressing),
					),
				).To(BeTrue())
				g.Expect(
					meta.IsStatusConditionTrue(
						fetched.Status.Conditions,
						string(kdexv1alpha1.ConditionTypeReady),
					),
				).To(BeTrue())
				cond := meta.FindStatusCondition(
					fetched.Status.Conditions,
					string(kdexv1alpha1.ConditionTypeProgressing),
				)
				g.Expect(cond.Message).To(Equal("Reconciliation successful"))
			}, "10s", "1s").Should(Succeed())
		})
	})
})

var _ = Describe("KDexFunction CEL validation", func() {
	Context("spec.backend admission", func() {
		ctx := context.Background()

		AfterEach(func() {
			cleanupResources(namespace)
		})

		It("rejects a function with both origin and backend set", func() {
			fn := &kdexv1alpha1.KDexFunction{
				ObjectMeta: metav1.ObjectMeta{
					Name:      "fn-both",
					Namespace: namespace,
				},
				Spec: kdexv1alpha1.KDexFunctionSpec{
					HostRef: corev1.LocalObjectReference{Name: focalHost},
					API: kdexv1alpha1.API{
						BasePath: "/v1/docs",
						Paths: map[string]kdexv1alpha1.PathItem{
							"/v1/docs/find": {Get: &runtime.RawExtension{Raw: []byte("{}")}},
						},
					},
					Origin: kdexv1alpha1.FunctionOrigin{
						Executable: &kdexv1alpha1.Executable{Image: "ghcr.io/example/fn:v1"},
					},
					Backend: &kdexv1alpha1.FunctionBackend{
						Type:    kdexv1alpha1.FunctionBackendTypeService,
						Service: &kdexv1alpha1.ServiceBackend{Name: "svc", Port: intstr.FromInt(80)},
					},
				},
			}
			err := k8sClient.Create(ctx, fn)
			Expect(err).To(HaveOccurred())
			Expect(err.Error()).To(ContainSubstring("mutually exclusive"))
		})

		It("rejects backend type=Service without backend.service", func() {
			fn := &kdexv1alpha1.KDexFunction{
				ObjectMeta: metav1.ObjectMeta{
					Name:      "fn-missing-service",
					Namespace: namespace,
				},
				Spec: kdexv1alpha1.KDexFunctionSpec{
					HostRef: corev1.LocalObjectReference{Name: focalHost},
					API: kdexv1alpha1.API{
						BasePath: "/v1/docs",
						Paths: map[string]kdexv1alpha1.PathItem{
							"/v1/docs/find": {Get: &runtime.RawExtension{Raw: []byte("{}")}},
						},
					},
					Backend: &kdexv1alpha1.FunctionBackend{
						Type: kdexv1alpha1.FunctionBackendTypeService,
					},
				},
			}
			err := k8sClient.Create(ctx, fn)
			Expect(err).To(HaveOccurred())
			Expect(err.Error()).To(ContainSubstring("service is required when type is Service"))
		})

		It("rejects service.path without leading slash", func() {
			fn := &kdexv1alpha1.KDexFunction{
				ObjectMeta: metav1.ObjectMeta{
					Name:      "fn-bad-path",
					Namespace: namespace,
				},
				Spec: kdexv1alpha1.KDexFunctionSpec{
					HostRef: corev1.LocalObjectReference{Name: focalHost},
					API: kdexv1alpha1.API{
						BasePath: "/v1/docs",
						Paths: map[string]kdexv1alpha1.PathItem{
							"/v1/docs/find": {Get: &runtime.RawExtension{Raw: []byte("{}")}},
						},
					},
					Backend: &kdexv1alpha1.FunctionBackend{
						Type: kdexv1alpha1.FunctionBackendTypeService,
						Service: &kdexv1alpha1.ServiceBackend{
							Name: "svc",
							Port: intstr.FromInt(80),
							Path: "api", // missing leading slash
						},
					},
				},
			}
			err := k8sClient.Create(ctx, fn)
			Expect(err).To(HaveOccurred())
			Expect(err.Error()).To(ContainSubstring("spec.backend.service.path"))
		})

		It("accepts a minimal Service-backed function", func() {
			fn := &kdexv1alpha1.KDexFunction{
				ObjectMeta: metav1.ObjectMeta{
					Name:      "fn-minimal",
					Namespace: namespace,
				},
				Spec: kdexv1alpha1.KDexFunctionSpec{
					HostRef: corev1.LocalObjectReference{Name: focalHost},
					API: kdexv1alpha1.API{
						BasePath: "/v1/docs",
						Paths: map[string]kdexv1alpha1.PathItem{
							"/v1/docs/find": {Get: &runtime.RawExtension{Raw: []byte("{}")}},
						},
					},
					Backend: &kdexv1alpha1.FunctionBackend{
						Type:    kdexv1alpha1.FunctionBackendTypeService,
						Service: &kdexv1alpha1.ServiceBackend{Name: "svc", Port: intstr.FromInt(80)},
					},
				},
			}
			Expect(k8sClient.Create(ctx, fn)).To(Succeed())
		})

		It("accepts named-port service", func() {
			fn := &kdexv1alpha1.KDexFunction{
				ObjectMeta: metav1.ObjectMeta{
					Name:      "fn-named-port",
					Namespace: namespace,
				},
				Spec: kdexv1alpha1.KDexFunctionSpec{
					HostRef: corev1.LocalObjectReference{Name: focalHost},
					API: kdexv1alpha1.API{
						BasePath: "/v1/docs",
						Paths: map[string]kdexv1alpha1.PathItem{
							"/v1/docs/find": {Get: &runtime.RawExtension{Raw: []byte("{}")}},
						},
					},
					Backend: &kdexv1alpha1.FunctionBackend{
						Type:    kdexv1alpha1.FunctionBackendTypeService,
						Service: &kdexv1alpha1.ServiceBackend{Name: "svc", Port: intstr.FromString("http")},
					},
				},
			}
			Expect(k8sClient.Create(ctx, fn)).To(Succeed())
		})
	})
})

var _ = Describe("Service-backed KDexFunction", func() {
	ctx := context.Background()

	BeforeEach(func() {
		// Ensure focalHost KDexInternalHost exists so the reconciler can find it.
		ensureFocalHost(ctx, namespace, focalHost)
	})

	AfterEach(func() {
		// cleanupResources doesn't know about Service/EndpointSlice — drain them
		// here so backend objects don't leak into sibling Describe blocks.
		Expect(k8sClient.DeleteAllOf(ctx, &corev1.Service{}, client.InNamespace(namespace))).To(Succeed())
		Expect(k8sClient.DeleteAllOf(ctx, &discoveryv1.EndpointSlice{}, client.InNamespace(namespace))).To(Succeed())
		Eventually(func(g Gomega) {
			// Exclude envtest's auto-managed "kubernetes" Service in default
			// namespace — the API-server bootstrap controller recreates it
			// almost immediately on delete, so DeleteAllOf can't clear it.
			// Only test-owned Services should remain absent.
			var svcs corev1.ServiceList
			g.Expect(k8sClient.List(ctx, &svcs, client.InNamespace(namespace))).To(Succeed())
			testSvcs := make([]corev1.Service, 0, len(svcs.Items))
			for _, s := range svcs.Items {
				if s.Namespace == "default" && s.Name == "kubernetes" {
					continue
				}
				testSvcs = append(testSvcs, s)
			}
			g.Expect(testSvcs).To(HaveLen(0))
			// Same exclusion as the Service check above: envtest's
			// auto-managed "kubernetes" Service owns an EndpointSlice in
			// the default namespace (kubernetes.io/service-name=kubernetes,
			// managed by kube-apiserver) that the bootstrap controller
			// recreates on delete — DeleteAllOf can't clear it. Only
			// test-owned slices should remain absent.
			var slices discoveryv1.EndpointSliceList
			g.Expect(k8sClient.List(ctx, &slices, client.InNamespace(namespace))).To(Succeed())
			testSlices := make([]discoveryv1.EndpointSlice, 0, len(slices.Items))
			for _, s := range slices.Items {
				if s.Namespace == "default" && s.Labels["kubernetes.io/service-name"] == "kubernetes" {
					continue
				}
				testSlices = append(testSlices, s)
			}
			g.Expect(testSlices).To(HaveLen(0))
		}, "5s", "200ms").Should(Succeed())
		cleanupResources(namespace)
	})

	makeServiceBacked := func(name string, svcName string, svcNs string) *kdexv1alpha1.KDexFunction {
		return &kdexv1alpha1.KDexFunction{
			ObjectMeta: metav1.ObjectMeta{Name: name, Namespace: namespace},
			Spec: kdexv1alpha1.KDexFunctionSpec{
				HostRef: corev1.LocalObjectReference{Name: focalHost},
				API: kdexv1alpha1.API{
					BasePath: "/v1/docs",
					Paths: map[string]kdexv1alpha1.PathItem{
						"/v1/docs/find": {Get: &runtime.RawExtension{Raw: []byte("{}")}},
					},
				},
				Backend: &kdexv1alpha1.FunctionBackend{
					Type: kdexv1alpha1.FunctionBackendTypeService,
					Service: &kdexv1alpha1.ServiceBackend{
						Name:      svcName,
						Namespace: svcNs,
						Port:      intstr.FromInt(8080),
						Scheme:    "http",
						Path:      "/api",
					},
				},
			},
		}
	}
	_ = makeServiceBacked // used by future tests (C3+); referenced now for compile

	It("becomes Ready when the Service and a ready endpoint exist", func() {
		// Create the backend Service.
		svc := &corev1.Service{
			ObjectMeta: metav1.ObjectMeta{Name: "knowdb", Namespace: namespace},
			Spec: corev1.ServiceSpec{
				Ports:    []corev1.ServicePort{{Name: "http", Port: 8080, TargetPort: intstr.FromInt(8080)}},
				Selector: map[string]string{"app": "knowdb"},
			},
		}
		Expect(k8sClient.Create(ctx, svc)).To(Succeed())

		// Create an EndpointSlice with one ready endpoint.
		ready := true
		es := &discoveryv1.EndpointSlice{
			ObjectMeta: metav1.ObjectMeta{
				Name:      "knowdb-1",
				Namespace: namespace,
				Labels:    map[string]string{discoveryv1.LabelServiceName: "knowdb"},
			},
			AddressType: discoveryv1.AddressTypeIPv4,
			Endpoints:   []discoveryv1.Endpoint{{Addresses: []string{"10.0.0.1"}, Conditions: discoveryv1.EndpointConditions{Ready: &ready}}},
			Ports:       []discoveryv1.EndpointPort{{Name: ptr.To("http"), Port: ptr.To[int32](8080)}},
		}
		Expect(k8sClient.Create(ctx, es)).To(Succeed())

		// Create the KDexFunction.
		fn := makeServiceBacked("fn-knowdb", "knowdb", "")
		Expect(k8sClient.Create(ctx, fn)).To(Succeed())

		Eventually(func(g Gomega) {
			fetched := &kdexv1alpha1.KDexFunction{}
			g.Expect(k8sClient.Get(ctx, client.ObjectKey{Name: fn.Name, Namespace: namespace}, fetched)).NotTo(HaveOccurred())
			g.Expect(fetched.Status.State).To(Equal(kdexv1alpha1.KDexFunctionStateReady))
			g.Expect(fetched.Status.URL).To(Equal("http://knowdb.default.svc.cluster.local:8080/api"))
			g.Expect(meta.IsStatusConditionTrue(fetched.Status.Conditions, string(kdexv1alpha1.ConditionTypeReady))).To(BeTrue())
		}, "10s", "500ms").Should(Succeed())
	})

	It("marks Ready=False with reason=ServiceNotFound when the Service does not exist", func() {
		fn := makeServiceBacked("fn-missing", "ghost-svc", "")
		Expect(k8sClient.Create(ctx, fn)).To(Succeed())

		Eventually(func(g Gomega) {
			fetched := &kdexv1alpha1.KDexFunction{}
			g.Expect(k8sClient.Get(ctx, client.ObjectKey{Name: fn.Name, Namespace: namespace}, fetched)).NotTo(HaveOccurred())
			cond := meta.FindStatusCondition(fetched.Status.Conditions, string(kdexv1alpha1.ConditionTypeReady))
			g.Expect(cond).NotTo(BeNil())
			g.Expect(cond.Status).To(Equal(metav1.ConditionFalse))
			g.Expect(cond.Reason).To(Equal("ServiceNotFound"))
			g.Expect(fetched.Status.URL).To(BeEmpty())
		}, "10s", "500ms").Should(Succeed())
	})

	It("resolves a named port to its numeric value in Status.URL", func() {
		svc := &corev1.Service{
			ObjectMeta: metav1.ObjectMeta{Name: "knowdb-named", Namespace: namespace},
			Spec: corev1.ServiceSpec{
				Ports:    []corev1.ServicePort{{Name: "api", Port: 9090, TargetPort: intstr.FromInt(9090)}},
				Selector: map[string]string{"app": "knowdb-named"},
			},
		}
		Expect(k8sClient.Create(ctx, svc)).To(Succeed())

		ready := true
		es := &discoveryv1.EndpointSlice{
			ObjectMeta: metav1.ObjectMeta{
				Name:      "knowdb-named-1",
				Namespace: namespace,
				Labels:    map[string]string{discoveryv1.LabelServiceName: "knowdb-named"},
			},
			AddressType: discoveryv1.AddressTypeIPv4,
			Endpoints:   []discoveryv1.Endpoint{{Addresses: []string{"10.0.0.2"}, Conditions: discoveryv1.EndpointConditions{Ready: &ready}}},
		}
		Expect(k8sClient.Create(ctx, es)).To(Succeed())

		fn := &kdexv1alpha1.KDexFunction{
			ObjectMeta: metav1.ObjectMeta{Name: "fn-named", Namespace: namespace},
			Spec: kdexv1alpha1.KDexFunctionSpec{
				HostRef: corev1.LocalObjectReference{Name: focalHost},
				API: kdexv1alpha1.API{
					BasePath: "/v1/docs",
					Paths:    map[string]kdexv1alpha1.PathItem{"/v1/docs/find": {Get: &runtime.RawExtension{Raw: []byte("{}")}}},
				},
				Backend: &kdexv1alpha1.FunctionBackend{
					Type: kdexv1alpha1.FunctionBackendTypeService,
					Service: &kdexv1alpha1.ServiceBackend{
						Name: "knowdb-named",
						Port: intstr.FromString("api"),
					},
				},
			},
		}
		Expect(k8sClient.Create(ctx, fn)).To(Succeed())

		Eventually(func(g Gomega) {
			fetched := &kdexv1alpha1.KDexFunction{}
			g.Expect(k8sClient.Get(ctx, client.ObjectKey{Name: fn.Name, Namespace: namespace}, fetched)).NotTo(HaveOccurred())
			g.Expect(fetched.Status.URL).To(Equal("http://knowdb-named.default.svc.cluster.local:9090/"))
		}, "10s", "500ms").Should(Succeed())
	})

	It("rejects an unknown named port with reason=InvalidPort", func() {
		svc := &corev1.Service{
			ObjectMeta: metav1.ObjectMeta{Name: "svc-noname", Namespace: namespace},
			Spec: corev1.ServiceSpec{
				Ports:    []corev1.ServicePort{{Name: "http", Port: 80}},
				Selector: map[string]string{"app": "x"},
			},
		}
		Expect(k8sClient.Create(ctx, svc)).To(Succeed())

		fn := &kdexv1alpha1.KDexFunction{
			ObjectMeta: metav1.ObjectMeta{Name: "fn-badport", Namespace: namespace},
			Spec: kdexv1alpha1.KDexFunctionSpec{
				HostRef: corev1.LocalObjectReference{Name: focalHost},
				API: kdexv1alpha1.API{
					BasePath: "/v1/docs",
					Paths:    map[string]kdexv1alpha1.PathItem{"/v1/docs/find": {Get: &runtime.RawExtension{Raw: []byte("{}")}}},
				},
				Backend: &kdexv1alpha1.FunctionBackend{
					Type: kdexv1alpha1.FunctionBackendTypeService,
					Service: &kdexv1alpha1.ServiceBackend{
						Name: "svc-noname",
						Port: intstr.FromString("does-not-exist"),
					},
				},
			},
		}
		Expect(k8sClient.Create(ctx, fn)).To(Succeed())

		Eventually(func(g Gomega) {
			fetched := &kdexv1alpha1.KDexFunction{}
			g.Expect(k8sClient.Get(ctx, client.ObjectKey{Name: fn.Name, Namespace: namespace}, fetched)).NotTo(HaveOccurred())
			cond := meta.FindStatusCondition(fetched.Status.Conditions, string(kdexv1alpha1.ConditionTypeReady))
			g.Expect(cond).NotTo(BeNil())
			g.Expect(cond.Reason).To(Equal("InvalidPort"))
			g.Expect(meta.IsStatusConditionTrue(fetched.Status.Conditions, string(kdexv1alpha1.ConditionTypeDegraded))).To(BeTrue())
		}, "10s", "500ms").Should(Succeed())
	})

	It("marks Ready=False with reason=NoEndpoints when no slice has ready endpoints", func() {
		svc := &corev1.Service{
			ObjectMeta: metav1.ObjectMeta{Name: "svc-noeps", Namespace: namespace},
			Spec: corev1.ServiceSpec{
				Ports:    []corev1.ServicePort{{Name: "http", Port: 8080}},
				Selector: map[string]string{"app": "x"},
			},
		}
		Expect(k8sClient.Create(ctx, svc)).To(Succeed())
		// Intentionally do not create an EndpointSlice.

		fn := makeServiceBacked("fn-noeps", "svc-noeps", "")
		Expect(k8sClient.Create(ctx, fn)).To(Succeed())

		Eventually(func(g Gomega) {
			fetched := &kdexv1alpha1.KDexFunction{}
			g.Expect(k8sClient.Get(ctx, client.ObjectKey{Name: fn.Name, Namespace: namespace}, fetched)).NotTo(HaveOccurred())
			cond := meta.FindStatusCondition(fetched.Status.Conditions, string(kdexv1alpha1.ConditionTypeReady))
			g.Expect(cond).NotTo(BeNil())
			g.Expect(cond.Status).To(Equal(metav1.ConditionFalse))
			g.Expect(cond.Reason).To(Equal("NoEndpoints"))
			g.Expect(fetched.Status.URL).To(BeEmpty())
		}, "10s", "500ms").Should(Succeed())
	})

	It("retains Status.URL when endpoints drop after the function is Ready", func() {
		svc := &corev1.Service{
			ObjectMeta: metav1.ObjectMeta{Name: "svc-flap", Namespace: namespace},
			Spec: corev1.ServiceSpec{
				Ports:    []corev1.ServicePort{{Name: "http", Port: 8080}},
				Selector: map[string]string{"app": "x"},
			},
		}
		Expect(k8sClient.Create(ctx, svc)).To(Succeed())

		ready := true
		es := &discoveryv1.EndpointSlice{
			ObjectMeta: metav1.ObjectMeta{
				Name:      "svc-flap-1",
				Namespace: namespace,
				Labels:    map[string]string{discoveryv1.LabelServiceName: "svc-flap"},
			},
			AddressType: discoveryv1.AddressTypeIPv4,
			Endpoints:   []discoveryv1.Endpoint{{Addresses: []string{"10.0.0.3"}, Conditions: discoveryv1.EndpointConditions{Ready: &ready}}},
		}
		Expect(k8sClient.Create(ctx, es)).To(Succeed())

		fn := makeServiceBacked("fn-flap", "svc-flap", "")
		Expect(k8sClient.Create(ctx, fn)).To(Succeed())

		// First become Ready.
		Eventually(func(g Gomega) {
			fetched := &kdexv1alpha1.KDexFunction{}
			g.Expect(k8sClient.Get(ctx, client.ObjectKey{Name: fn.Name, Namespace: namespace}, fetched)).NotTo(HaveOccurred())
			g.Expect(fetched.Status.State).To(Equal(kdexv1alpha1.KDexFunctionStateReady))
			g.Expect(fetched.Status.URL).NotTo(BeEmpty())
		}, "10s", "500ms").Should(Succeed())

		// Drop the endpoint to unready.
		notReady := false
		es.Endpoints[0].Conditions.Ready = &notReady
		Expect(k8sClient.Update(ctx, es)).To(Succeed())

		// URL stays; Ready flips False with reason=NoEndpoints.
		Eventually(func(g Gomega) {
			fetched := &kdexv1alpha1.KDexFunction{}
			g.Expect(k8sClient.Get(ctx, client.ObjectKey{Name: fn.Name, Namespace: namespace}, fetched)).NotTo(HaveOccurred())
			cond := meta.FindStatusCondition(fetched.Status.Conditions, string(kdexv1alpha1.ConditionTypeReady))
			g.Expect(cond).NotTo(BeNil())
			g.Expect(cond.Status).To(Equal(metav1.ConditionFalse))
			g.Expect(cond.Reason).To(Equal("NoEndpoints"))
			g.Expect(fetched.Status.URL).NotTo(BeEmpty(), "URL must be retained on transient drop")
		}, "10s", "500ms").Should(Succeed())
	})

	It("clears Status.URL when the Service is deleted after Ready", func() {
		svc := &corev1.Service{
			ObjectMeta: metav1.ObjectMeta{Name: "svc-delete", Namespace: namespace},
			Spec: corev1.ServiceSpec{
				Ports:    []corev1.ServicePort{{Name: "http", Port: 8080}},
				Selector: map[string]string{"app": "x"},
			},
		}
		Expect(k8sClient.Create(ctx, svc)).To(Succeed())

		ready := true
		es := &discoveryv1.EndpointSlice{
			ObjectMeta: metav1.ObjectMeta{
				Name:      "svc-delete-1",
				Namespace: namespace,
				Labels:    map[string]string{discoveryv1.LabelServiceName: "svc-delete"},
			},
			AddressType: discoveryv1.AddressTypeIPv4,
			Endpoints:   []discoveryv1.Endpoint{{Addresses: []string{"10.0.0.4"}, Conditions: discoveryv1.EndpointConditions{Ready: &ready}}},
		}
		Expect(k8sClient.Create(ctx, es)).To(Succeed())

		fn := makeServiceBacked("fn-delete", "svc-delete", "")
		Expect(k8sClient.Create(ctx, fn)).To(Succeed())

		Eventually(func(g Gomega) {
			fetched := &kdexv1alpha1.KDexFunction{}
			g.Expect(k8sClient.Get(ctx, client.ObjectKey{Name: fn.Name, Namespace: namespace}, fetched)).NotTo(HaveOccurred())
			g.Expect(fetched.Status.URL).NotTo(BeEmpty())
		}, "10s", "500ms").Should(Succeed())

		Expect(k8sClient.Delete(ctx, svc)).To(Succeed())
		Expect(k8sClient.Delete(ctx, es)).To(Succeed())

		Eventually(func(g Gomega) {
			fetched := &kdexv1alpha1.KDexFunction{}
			g.Expect(k8sClient.Get(ctx, client.ObjectKey{Name: fn.Name, Namespace: namespace}, fetched)).NotTo(HaveOccurred())
			cond := meta.FindStatusCondition(fetched.Status.Conditions, string(kdexv1alpha1.ConditionTypeReady))
			g.Expect(cond).NotTo(BeNil())
			g.Expect(cond.Reason).To(Equal("ServiceNotFound"))
			g.Expect(fetched.Status.URL).To(BeEmpty(), "URL must be cleared on hard failure")
			g.Expect(meta.IsStatusConditionTrue(fetched.Status.Conditions, string(kdexv1alpha1.ConditionTypeDegraded))).To(BeTrue())
		}, "10s", "500ms").Should(Succeed())
	})

	It("clears build-related status fields when spec switches from origin to backend", func() {
		// Pre-seed a function with origin set and stale build status.
		fn := &kdexv1alpha1.KDexFunction{
			ObjectMeta: metav1.ObjectMeta{Name: "fn-switch", Namespace: namespace},
			Spec: kdexv1alpha1.KDexFunctionSpec{
				HostRef: corev1.LocalObjectReference{Name: focalHost},
				API: kdexv1alpha1.API{
					BasePath: "/v1/docs",
					Paths:    map[string]kdexv1alpha1.PathItem{"/v1/docs/find": {Get: &runtime.RawExtension{Raw: []byte("{}")}}},
				},
				Origin: kdexv1alpha1.FunctionOrigin{
					Executable: &kdexv1alpha1.Executable{Image: "ghcr.io/example/initial:v1"},
				},
			},
		}
		Expect(k8sClient.Create(ctx, fn)).To(Succeed())

		// Inject stale build status (mirroring what the Origin-based reconciler would set).
		// The reconciler may race us on its own status updates, so retry on conflict.
		Eventually(func(g Gomega) {
			fetched := &kdexv1alpha1.KDexFunction{}
			g.Expect(k8sClient.Get(ctx, client.ObjectKey{Name: fn.Name, Namespace: namespace}, fetched)).NotTo(HaveOccurred())
			fetched.Status.Executable = &kdexv1alpha1.Executable{Image: "stale:image"}
			g.Expect(k8sClient.Status().Update(ctx, fetched)).NotTo(HaveOccurred())
		}, "5s", "100ms").Should(Succeed())

		// Create the new backend Service and slice.
		svc := &corev1.Service{
			ObjectMeta: metav1.ObjectMeta{Name: "switched-svc", Namespace: namespace},
			Spec: corev1.ServiceSpec{
				Ports:    []corev1.ServicePort{{Name: "http", Port: 8080}},
				Selector: map[string]string{"app": "x"},
			},
		}
		Expect(k8sClient.Create(ctx, svc)).To(Succeed())
		ready := true
		es := &discoveryv1.EndpointSlice{
			ObjectMeta: metav1.ObjectMeta{
				Name:      "switched-svc-1",
				Namespace: namespace,
				Labels:    map[string]string{discoveryv1.LabelServiceName: "switched-svc"},
			},
			AddressType: discoveryv1.AddressTypeIPv4,
			Endpoints:   []discoveryv1.Endpoint{{Addresses: []string{"10.0.0.5"}, Conditions: discoveryv1.EndpointConditions{Ready: &ready}}},
		}
		Expect(k8sClient.Create(ctx, es)).To(Succeed())

		// Switch spec: drop origin, set backend. The reconciler may concurrently bump
		// the resourceVersion via its own status updates, so retry on conflict using
		// Eventually instead of a fixed sleep.
		Eventually(func(g Gomega) {
			updated := &kdexv1alpha1.KDexFunction{}
			g.Expect(k8sClient.Get(ctx, client.ObjectKey{Name: fn.Name, Namespace: namespace}, updated)).NotTo(HaveOccurred())
			updated.Spec.Origin = kdexv1alpha1.FunctionOrigin{} // empty; Origin is a value type, so we zero its subfields
			updated.Spec.Backend = &kdexv1alpha1.FunctionBackend{
				Type:    kdexv1alpha1.FunctionBackendTypeService,
				Service: &kdexv1alpha1.ServiceBackend{Name: "switched-svc", Port: intstr.FromInt(8080)},
			}
			g.Expect(k8sClient.Update(ctx, updated)).NotTo(HaveOccurred())
		}, "5s", "100ms").Should(Succeed())

		Eventually(func(g Gomega) {
			final := &kdexv1alpha1.KDexFunction{}
			g.Expect(k8sClient.Get(ctx, client.ObjectKey{Name: fn.Name, Namespace: namespace}, final)).NotTo(HaveOccurred())
			g.Expect(final.Status.State).To(Equal(kdexv1alpha1.KDexFunctionStateReady))
			g.Expect(final.Status.URL).To(Equal("http://switched-svc.default.svc.cluster.local:8080/"))
			g.Expect(final.Status.Executable).To(BeNil(), "Executable must be cleared after switch to Service-backed")
		}, "10s", "500ms").Should(Succeed())
	})
})
