package internal

import "k8s.io/apimachinery/pkg/runtime/schema"

const (
	// ANNOTATION_GENERATION stamps the observed .metadata.generation onto
	// generated children so a stale one can be told from a current one. It is
	// written in four packages and read in a fifth; a typo in any of them
	// silently makes every child look stale.
	ANNOTATION_GENERATION = "kdex.dev/generation"
	// LABEL_DEFAULT marks the cluster-scoped resource to fall back to when a
	// host names none. Used as a List selector, where a typo silently matches
	// nothing rather than failing.
	LABEL_DEFAULT = "kdex.dev/default"

	AUTOGENERATED_INDEX_KEY = "spec.metadata.autoGenerated"
	BACKEND                 = "backend"
	CACHE_DIR               = "/cache"
	CACHE_VOLUME            = "package-cache"
	HOST_INDEX_KEY          = "spec.hostRef.name"
	MODULE_PATH             = "/-/modules"
	OCI_IMAGE               = "oci-image"
	PAGE_FINALIZER          = "kdex.dev/kdex-host-page-finalizer"
	SHARED_VOLUME           = "shared-volume"
	SUB_INDEX_KEY           = "spec.subject"
	TRANSLATION_FINALIZER   = "kdex.dev/kdex-host-translation-finalizer"
	WORKDIR                 = "/shared"
)

var KPackImageGVK = schema.GroupVersionKind{
	Group:   "kpack.io",
	Version: "v1alpha2",
	Kind:    "Image",
}
